---
name: TR-2026-05_사전등록_v1.0
description: 같은 셀(셀 A 왕복 컨베이어 · 셀 B(3i) 분류 셀)을 빠른 이송 모형과 MuJoCo 물리 모형으로 돌려, 알려진 결함 래더의 검출과 정답 래더 판정이 모형에 따라 얼마나 뒤바뀌는지를 묻는 가상 실험(E2) — 사전 등록 고정판 v1.0(예측 · 분석 동결 v0.6 · 개정 1 반영, 공식 실행 전)
type: project
작성일: 2026-10-08
버전: v1.0 (고정 — 공식 실행 전). [동결] 절은 v0.6 과 바이트가 같다(동결 절 sha256 888cfd52…). v0.6 → v1.0 변경은 「동결 뒤 변경」 표와 끝의 「v1.0 변경 기록」
---

# TR-2026-05 사전 등록 v1.0 — 빠른 이송 모형과 MuJoCo 모형의 PLC 래더 판정 차이 (E2)

| 항목 | 내용 |
| --- | --- |
| 작성 | 2026-10-08 [책임 저자: 방동걸] — 초안 작성 · 개정은 LLM 코딩 에이전트 |
| 상태 | **고정.** 공식 실행 전. 공식 시드는 시드 표를 만들려고 적재만 했고(F 1 + M 18 설정) 플랜트를 한 틱도 돌리지 않았다. 교정 · M1 재생성 · 양성 대조 1 · 2 는 동결 뒤에 끝냈다(§4-4). 이 판의 sha256 을 공개 저장소에 커밋한 뒤에만 공식 회차를 돈다(§14) |
| 예측 · 분석 동결 | v0.6(`TR-2026-05_사전등록_v0.6.md`, 파일 sha256 `0ff68e055e5ea39ddc4d5d6ede2d79fc391a11426122527ebb7ebbe4895949ed`, 동결 절 sha256 `888cfd52dc465f901c0e65cda43529cf8dd32ba7baeb55c4cff41ec9661e9418`) — 공개 저장소 tech-reports 커밋 `3a12187a08204d6afb95d62edc589cda0c3f0ce5`(2026-10-08 13:33:43 KST). 이 판의 [동결] 절 9개(§1 · §3 · §5 · §6 · §7 · §8 · §9 · §11 · §13)는 v0.6 과 바이트가 같다 — 같은 규칙(`_agent/TR-05_v0.6_동결범위_2026-10-08.md`)으로 잘라 다시 계산한 값이 위 값과 같음을 확인했다 |
| 개정 1 | `TR-2026-05_사전등록_개정1_2026-10-08.md`(sha256 `8b68148fc2b93e7bf756aabee73dd5357212f8a15ba3be9aeec17749e22bccdb`) — 공개 저장소 tech-reports 커밋 `1ac8c13`(2026-10-08 13:55:28 KST). 동결 뒤 · 공식 실행 전. 참조 일치 무효 기준(§8 ②)의 비교 대상에서 F · M0 참조 논리에도 반 스캔 안쪽 여유 표기를 쓴다(「동결 뒤 변경」 표 1행). [동결] 절의 문장은 고치지 않았고, 개정 1 이 그 절들의 해당 규칙에 우선한다 |
| 근거 | 대표 2026-10-08 「tr-05는 진행함」(`TR-2026-05_재개계획_2026-10-08.md`) — 작업 재개 지시. 경로 A · 범위 셀 A · B(3i)는 그 계획을 따른다. 작성 중 결정 D1~D19 · L1~L3 과 구현 단계 결정 (a)~(i)(v0.6 변경 기록)는 리드가 정했다 |
| 대표 확인 | 대표 2026-10-08 「추천대로」 — 결과와 무관하게 보고서 · 공개본 결과 · 실행기 공개 범위대로 공개 승인. 같은 답으로 MuJoCo 이송 규칙 · 모형을 특허 출원 없이 이 편으로 공개하는 것(§12 「특허 · 방어적 공개」)도 승인. 해시 공개 커밋 · 공식 실행 환경(우분투 PC 한 대)은 이 승인 범위의 절차로 본다. 이 행의 결정은 실험 설계(§1~§9)를 바꾸지 않는다 |
| 레포 | vexplor-vision-2 `feature/tr05-e2` 커밋 `ac78d02fbc84b35f041f4fcca2047a0c80c67930`(E2-4) — 공식 빌드(§10). 그 아래 `0edb740` · `ab5d3c9` · `67cd39b` · `23e5e86` · `579eddb`(main `af2d3ef` + `feature/external-control` 병합). 개발 브랜치이며 main 에 병합되지 않았다 |
| 이전 판 · 검토 | v0.2(보류) · v0.3 초안 · v0.4 · v0.5 · v0.6(2026-10-08). v0.4 교차 검토 4건(설계 11 · 산술 13 · 공개 위험 5 · 도메인 7)과 편차 기록 `_agent/TR-05_교차종합_2026-10-08.md`. 구현 검토: 앱 `e2_review_4.md`(반드시 2 · 권고 5 — 모두 반영), 실행기 자기 시험 13종 |
| 심사 | 동료 심사 없음. 검토는 서로의 산출과 작성 맥락을 읽지 않은 AI 에이전트 실행이며 사람 검토자는 없다 |

## 동결 뒤 변경 (v0.6 동결 커밋 `3a12187` 뒤 — 모두 공식 실행 전)

| 번호 | 무엇 | 왜 | 언제 | 동결 절에 주는 영향 |
| --- | --- | --- | --- | --- |
| 1 | **개정 1** — F · M0 의 참조 논리도 M1 과 같이 창 경계를 반 스캔 안쪽 여유 표기로 비교한다. 적용 값(원래 상수 그대로, 표기만): 슈트 확인 창 165~235 → `chute_confirm_delay_s` 2.0 · `chute_confirm_tolerance_s` 0.3525, 출력 확인 창 198~269 → 2.335 · 0.3575(원래 2.3333… ± 0.35 는 경계 198 · 269 에서 래더와 어긋남), 슈트 가득 45 → `full_hold_s` 0.445. M1 매개변수표는 그 위에 덮어쓴다. 구현은 `bridge/refcheck.py` 의 `base_margin()`(설계값이 래더 정수 상수와 1 스캔 넘게 다르면 멈춤), `logic.py` 는 고치지 않음 | 양성 대조 2(개발 시드 2617252722, M0)에서 래더는 정수로 슈트 확인 대기 초과를 나이 236 = 틱 1697 에 냈는데, 원래 참조 논리는 실수 비교(16.96 − 14.61 = 2.3500000000000014 > 2.35)로 한 스캔 일찍(틱 1696) 잠가 첫 잠금 전 참조 차이 1건이 생겼다. §8 ② 를 쓰인 대로 적용하면 확인 대기 초과로 처음 잠그는 실행 하나로 회차 전체가 판정과 무관하게 무효가 된다. v0.6 §3-5 괄호가 예상한 「원래 2.0 ± 0.35 도 경계 나이에서 정수 창과 어긋난다」가 원래 상수 조건에서 실제로 일어났다 | 2026-10-08, 공개 저장소 `1ac8c13`(13:55:28 KST). 공식 시드로 플랜트를 돌리기 전 | §3-5 · §8 ② 의 비교 대상(참조 논리 매개변수)만 바뀜. 래더 · 플랜트 · 판정 규칙 · 예측 · 판정선(§7) · 분석 계획(§9)은 그대로. [동결] 절의 바이트는 그대로이고 개정 1 이 우선한다 |
| 2 | 회차 실행기 `round.py run --dev` 수정 — 시드 표를 주면 개발 시드 집합을 쓴다(전에는 공식 집합을 읽었음) | 양성 대조 2 가 개발 시드가 아니라 공식 시드를 돌릴 뻔한 결함. 공식 회차 경로는 바뀌지 않음 | 양성 대조 2 첫 실행 전(동결 뒤) | 없음(실행기 코드, [동결] 절 밖) |
| 3 | 고정값 파일 범위 확장(`round.py fixed`) — 앱 쪽 입력(셀 파일 · io-map · asm-pusher 1.5.0 `device.json` · `logic.py` · 분류 기준 JSON · `phase3c-control.json`), vendor 트리 · Node 판 · E4 변종 목록 2개 · `SOURCES.json` · 시드 표 · 교정 기록을 함께 고정하고 시작 전에 확인 | §8 「실행 시작 전 거부」가 열거한 입력 가운데 v0.6 고정값 파일이 담지 않던 것을 담기 위해 | 양성 대조 2 첫 실행 전 | 없음(§8 의 거부 대상을 실제로 덮게 함) |
| 4 | `refcheck.py` · `run.py` 수정(개정 1 구현), `SOURCES.json` 재생성(62 파일), 고정값 파일 재생성 | 개정 1 | 개정 1 커밋 뒤, 양성 대조 2 재실행 전 | 없음 |
| 5 | `SOURCES.json` 의 `fixed.json` 줄은 **초안 고정값 파일의 해시 `0d2d2e40149c474788875e698ec1decb14bc73c7efcbf350eb68bdcdeaa692af`** 를 담고 있다. 정본 고정값 파일은 `532167ac1078b01ea5b4b9a42dd3ca2879a3d23e707dccab9c89b8024eae4442` 다 | 고정값 파일이 `SOURCES.json` 의 해시를 담으므로, `SOURCES.json` 을 다시 만들면 고정값 파일이 바뀌고 다시 `SOURCES.json` 이 바뀌는 순환이 생긴다. 그래서 `SOURCES.json` 을 마지막으로 만든 뒤 고정값 파일을 만들고, `SOURCES.json` 은 다시 만들지 않았다. 고정값 파일의 정본 해시는 이 표와 §10 이 정한다 | 최종 고정값 파일 생성 때 | 없음 |
| 6 | 양성 대조 1 의 회귀 시험 ①은 같은 실행 파일로 돈 기존 ctest 11/11 기록(13:09)을 썼다(빌드 폴더를 고치지 않으려고 새로 돌리지 않음) | §8 ①은 「공식 빌드에서 통과」를 요구 — 같은 실행 파일(d58c3928…)의 기록이다 | 양성 대조 1 | 없음 |

## 1. 질문 [동결]

같은 셀 정의 · 같은 PLC 래더 · 같은 자극으로, 부품 이송을 **빠른 이송 모형**(plc-devices 코어의 운동학 규칙)으로 계산할 때와 **MuJoCo 모형**(벨트 데크 · 가이드 · 슈트 위 상자를 강체 접촉으로 계산)으로 계산할 때,

1. **결함 검출**: 알려진 결함을 넣은 래더(음성 래더)를 각 모형이 몇 건 검출하는가, 검출이 엇갈리는 쌍은 몇 개인가.
2. **정답 래더 판정의 뒤바뀜**: 정답 래더의 판정([PASS]/[FAIL])이 모형에 따라 몇 건 뒤바뀌는가, 그 방향과 원인(처음 갈라진 사건)은 무엇인가.
3. 2 의 뒤바뀜이 **정답 래더 상수를 MuJoCo 모형으로 다시 구한 뒤에도** 남는가(조건 M1, §6-1).

여기서 **모형 M 은 MuJoCo 접촉 계산 하나가 아니라 묶음이다** — MuJoCo 강체 접촉(§10 엔진 설정), 이식 규칙(규칙 v1 · v4, 접촉 허용치 2 mm 둘, `CHUTE-HOLD`, 슈트 x 힘), 가정 물리값(§10 목록), 그리고 F 에만 있는 규칙의 부재(§3-2 「다름」 행). 이 편의 확인 주장은 「모형 선택(이 묶음)이 판정을 바꾼다」까지이고, 그 원인을 「물리」와 「이식 · 규칙 · 장부 차이」로 나누는 것은 §7 의 원인 분류와 §8 E1 의 사전 대응표로만 한다.

**어느 모형이 옳은지는 정하지 않는다.** 실물 셀이 없으므로 「MuJoCo 가 더 사실적이다」를 주장하지 않는다. 이 편은 플랜트 모형 하나만 바꿨을 때 래더 판정이 바뀌는지, 몇 건이 어디서 바뀌는지를 잰다. 정답 래더의 일부 상수는 빠른 이송 모형의 계산 이력에 맞춰 정해졌으므로(§3-3), MuJoCo 에서 [FAIL] 이 나오면 그것이 래더의 결함인지 상수 출처의 효과인지 구별해야 한다 — 그래서 조건 M1 을 둔다.

이 문서의 사내 이름: E2 = 이 실험의 사내 번호. 경로 A = 부품 이송만 MuJoCo 로 계산하고 액추에이터는 빠른 모형과 같은 코드를 쓰는 구성(§3). 3i · 3j · 3k = 셀 B 설계 · 래더의 사내 단계(3i 가 가장 앞선 판, §3-3). D · L · U · N 번호 = 사전 등록 작성 중 결정 · 가정 기록의 번호(공개하지 않음).

## 2. 왜 가상 실험인가

- 같은 래더 · 같은 자극 · 같은 부품 배치에서 플랜트 모형만 바꿔 나란히 돌릴 수 있다. 액추에이터(푸셔 실린더 궤적 · 벨트 모터 · 센서 판정 코어)는 두 모형이 같은 코드를 쓴다(경로 A, §3).
- 두 모형의 비교(주 결과)는 같은 기계 · 같은 빌드 안에서만 이루어진다. 판정의 절대값(어느 래더가 [PASS] 인지)은 셀 정의 · 가정 물리값(§10)에 달려 있어 현장 값을 말하지 않는다.
- 이 편은 실물 PLC · 실물 컨베이어 · 실물 상자에 대해 아무것도 말하지 않는다.

## 3. 대상 코드의 현재 동작 (소스 판독) [동결]

### 3-1. 두 모형

| 항목 | 빠른 이송(F) | MuJoCo(M) — `--physics mujoco` |
| --- | --- | --- |
| 선택 | 기본값 | CLI `--physics fast\|mujoco` > 환경 변수 `VEXPLOR_EXTCTL_PHYSICS` > 셀 JSON `"physics":{"mode","values"}` > fast. 적재 때 stderr 한 줄 `EXTCTL_PHYSICS mode=… source=cli\|env\|cell\|default` |
| 셀 A (왕복, 50 ms 틱) | plc-devices 벨트 코어가 부품 x 를 직접 옮김 | 데크(정적 상자, 1 ms 마다 코어 모터의 벨트 변위로 표면 속도) · 양옆 가이드(가이드 틈에서 분할) · 바닥 · 부품 1개(동적 상자). 1 ms 고정 스텝 × 50. 부품 자세 → 기존 sen-photo 코드. PART_DROP 은 코어와 같은 규칙(1 ms 표본에서 처음 \|x\| > L/2 + 1e-12). 부품의 측면 위치(배치 transform z)가 0 이 아니면 적재를 거부한다(셀 A 코어 · 장면 모두 z 를 0 에 고정) |
| 셀 B(3i) (분류, 10 ms 틱) | `FlyingPlant`(plc-devices 3e/3g 코어): 벨트 이송 · 센터링 클램프 · 날아가는 푸셔 이송 · 원호 · 슈트 상한 · 브레이크 · 출력 누적 상한 | 데크 5개(feed3 · feed2 · feed1 · conveyor · outputBelt, 모두 conveyor 모터 하나가 구동, 데크 사이 이음 4 cm) · 센터링 벽 · 원호 10면 · 20° 슈트 · 슈트 옆벽 · 끝벽 · 출력 끝 쿠션 · 바닥 · 상자 20개(동적). 푸셔 판은 코어 실린더 궤적을 1 ms 경계마다 위치 · 속도로 써 넣은 자유 동적 상자(추종 오차 최대 0.025 mm). 1 ms × 10. 부품 배치 transform z(측면 위치)는 F · M 모두 `<part>.initial_z` 로 읽는다(0 이면 키를 넣지 않음) |
| 액추에이터 · 센서 | 코어 | **같은 코어**(벨트 모터 · 푸셔 실린더 타이밍 · 리드 스위치 · 고장 · 커튼 · 패널 · sen-photo · HMI 계수). 센서는 기본으로 축 정렬 고정 치수 상자 + MuJoCo 부품 중심(회전은 넣지 않음). 감도 설정 `sensor_footprint_rotated=1` 이면 네 센서(inspection · atStopper · out · chuteSensor) 모두에, MuJoCo 자세(틱 끝 사원수)로 돌린 부품 상자를 그 센서 광학 좌표계로 옮긴 축 정렬 외접 상자(반폭_i = Σ_j \|M_ij\| · 반치수_j, M = rᵀR)를 넣는다. 중심은 그대로 부품 중심. F 는 이 분기에 들어가지 않는다 |
| 원자 스텝 | 틱마다 플랜트 복사 → 성공 시 확정 | 같음. 복사는 MuJoCo 모델 · 데이터의 깊은 복제(`World::clone`) |
| 수치 이상 | — | autoreset 끔. 1 ms 스텝에서 MuJoCo 경고가 하나라도 나면 예외 → 그 틱은 확정되지 않음(§8 `[PLANT_ERROR]`) |
| 해시 ① 물리값 해시 | — | `state.physics.values_sha256`: 규칙 문자열(A `transport_rule=v1`, B `transport_rule=v4` 전문) + 이름 붙은 값 목록(A 15개, B 32개) + 실제 컴파일된 장면 MJCF 전문 + 컴파일된 옵션 + 엔진 버전. 셀 B 는 모든 플랜트 매개변수(부품 분류 · 측면 위치 포함, `report.*` 제외)도 넣으므로 배치(시드) · 벨트 배율 · 초기 측면 위치마다 다르다. 셀 A 는 플랜트 매개변수를 넣지 않는다(벨트 배율로도 바뀌지 않음) |
| 해시 ② 설정 해시 | — | `state.physics.setup_sha256`: 규칙 문자열 + 값 목록 + 컴파일된 옵션 + 엔진 버전만. 장면 MJCF · 플랜트 매개변수 제외 → 셀 B 에서도 시드와 무관한 등록값 하나(§10). 물리값을 바꾸면 바뀌고, 셀 매개변수(벨트 배율 · 초기 위치)로는 바뀌지 않는다 |
| 보고 ① 부품별 상태(판정 · 규칙 · 해시가 읽지 않음) | `state.parts` 의 위치(기존 키, 회전 없음) | `state.physics.parts[]` — 틱 끝마다, 적재 응답(틱 0)부터. 대상은 셀 B 의 route 0 · 1 · 2 · 4 부품 전부, 셀 A 의 route 0 부품. 원소 `{id, route, body(dynamic\|held\|inactive), position[x,y,z], quaternion[w,x,y,z](부호 그대로), velocity[vx,vy,vz], yaw_rad, tilt_rad, slope_angle_rad, slope_velocity_mps, support(deck\|arc\|slope\|floor), support_gap_m, stacked, on_floor}`. yaw_rad = 몸체 x 축의 +y 둘레 방위(부호 있음), tilt_rad = 몸체 위축과 +y 사이 각. **slope_velocity_mps** = v·(0, −sin θ, cos θ), θ = 지지면 국소 내리막 각(데크 · 바닥 0, 원호 asin(clamp((z − lip)/(R + h/2), 0, sin A)), 경사면 A = 20°). **support**: 중심 z > 앞턱이고 슈트 폭 안이면 원호 · 경사면(중심 기준), 아니면 **상자 발자국의 x 구간 [x − L/2, x + L/2] 이 어느 데크와 겹치면 deck(이음 위 포함)**, 그 밖은 floor. **support_gap_m** = 중심 높이 − 그 지지면 위에 쉬는 상자의 중심 높이(데크: 데크 윗면 + h/2, 원호 · 경사면: 빠른 코어 `transfer_support_y` 와 같은 식(기울기 포함), 바닥: h/2). **stacked** = support_gap_m > 0.03 ∧ 다른 부품과 접촉, **on_floor** = 바닥과 접촉. 접촉은 MuJoCo 접촉 목록이며 시점이 셀마다 다르다 — 셀 B 는 그 틱 마지막 하위 스텝의 시작 상태(기본 스텝에서 틱 끝보다 1 ms 앞), 셀 A 는 틱 끝 상태. 위치 · 속도는 두 셀 모두 틱 끝 값 |
| 보고 ② 첫 판-상자 접촉(판정 · 규칙 · 해시가 읽지 않음) | `state.fast_first_contact` — **앱에 `--report-first-contact` 를 줄 때만** 생긴다(적재 응답부터 `[]`). 플래그가 없으면 F 응답은 바이트 단위로 바뀌지 않고, 플래그를 줘도 이 키 밖의 응답은 바이트가 같다. **실행기는 모든 F 실행에 이 플래그를 준다**(결정 (a)). 원소 형식은 M 과 같다. 기준: 플레이트 규칙이 밀기로 선택한 부품만, `transfer_step` 이 그 상자를 판으로 처음 옮긴 1 ms 표본과 그 표본의 상자 중심 x | `state.physics.first_contact[]`(셀 B, 셀 A 는 항상 `[]`). 원소 `{part(1부터), tick, ms(1..10), t_s, x}`, 정렬 (tick, ms, part). 기준: **플레이트 규칙이 밀기로 선택한 부품만**, 선택 틱(`select:touching`)의 가장 이른 판-부품 접촉 표본(그 틱에 접촉이 없으면 다음 접촉), x = 그 표본의 상자 중심 x(분류 위치 x = 0). 선택 전의 옆면 · 복귀 접촉은 기록하지 않는다. 표본 규칙: 1 ms 마다 첫 하위 스텝을 따로 밟은 뒤 접촉 목록을 읽으므로, 어느 `fixed_step_s` 에서도 기록 표본은 정확히 「그 ms 시작 자세 = 표본 ms」다(표본 0 은 앞 틱의 ms 10) |
| 범위 밖 | — | 포장 셀(`pack.enabled`)과 셀 B 3j/3k 변형(`feed_boundary_m` · `collection_lift_m` · `hsc_pitch_m` 이 있는 설계 = asm-pusher 1.6.0)은 MuJoCo 모드를 거부한다 |

### 3-2. 두 모형의 차이 (기능 목록 표)

판정 규칙은 「빠른 코어의 같은 식을 MuJoCo 상태에 적용」이 원칙이다(코어 출처 파일 · 줄은 개발 기록). 같지 않은 것은 아래에 모두 적는다. 「같은가」 칸의 값은 §8 E1 의 원인 대응표에 그대로 쓴다.

| 행 | 기능 | F | M | 같은가 |
| --- | --- | --- | --- | --- |
| r1 | 벨트 위 이송 | x += 벨트 변위 | 표면 속도 + 접촉 마찰(셀 B 데크는 정지 마찰 가중 1 — 미는 동안의 미끄럼에도 μs) | 접촉 계산으로 바꿈 |
| r2 | 부품 회전(yaw · 기울기) | 자유도 없음 | 있음. 기본 센서에는 넣지 않음. 보고는 `parts[]` 전체 자세 | 다름 |
| r3 | 푸셔가 미는 동작 | `transfer_step` 운동학 | 판과 상자의 접촉 | 접촉 계산으로 바꿈 |
| r4 | 슈트 x 방향 마찰 `chute_x_mu` 0.85 | x 감속 규칙 | 등방 마찰(경사 0.3 · 원호 0.15) + 슈트 부품 무게중심에 x 방향 추가 힘(규칙 v4, `chute_x_force=0` 이면 끔). `transition_mu_scale` 은 원호 면 마찰과 슈트 x 힘이 빼는 원호 등방분에 같은 배율을 곱하므로, `chute_x_force=1` 에서 원호 위 x 총 감속은 chute_x_mu·g 로 남고 바뀌는 것은 원호의 경사 방향 마찰과 yaw 다. 힘이 무게중심에만 걸려 실제 이방성 마찰이 주는 yaw 감쇠 토크가 없다(M 의 슈트 위 yaw 를 키우는 쪽) | 근사 |
| r5 | 슈트 대기열 상한 · 간격 · 끝 브레이크(끝 0.9 m, 5 m/s²) | 규칙 | 끝벽 · 상자끼리 접촉만 | 다름 |
| r6 | `chute.jam` | 슈트 부품 정지(cap = z) | 슈트 부품을 그 자세로 붙잡음(`CHUTE-HOLD`) | 같은 효과를 내도록 옮김 |
| r7 | 슈트 포착(route 1) | 중심 z > 앞턱 | 같은 기준, 틱 끝 | 같음 |
| r8 | 출력 도착(route 2) | 상한에 맞춰 정렬 | 접촉 정지 위치가 상한에서 2 mm 안(`output_contact_tolerance_m`). 경로 집계 · 다음 상자 상한에만 쓰고 PLC 센서 입력에는 쓰지 않음. 누적 상자가 벨트 마찰을 계속 받아 줄이 휠 수 있고, 휜 줄 뒤 상자는 route 0 으로 남을 수 있다 | 허용 오차를 더함 |
| r9 | CENTER-ENTRY | 식 | 같은 식. 단 가이드(±0.2 m) 때문에 M 에서는 일어날 수 없고 \|z\| > 0.125 m 초기 배치는 겹침으로 거부 | 범위 제외(§5) |
| r10 | CENTER-SNAP | 앞 모서리 식 + z 클램프 | 발자국 가장 깊은 모서리(yaw 포함) − 2 mm 접촉 허용(`center_contact_tolerance_m`, 측정 최대 1.66 mm — 여유 0.34 mm). 양성 사례는 어느 모형에서도 시험되지 않음 | 근사 |
| r11 | FLY-SIDE · PUSH-RETURN | 사건만 기록, 판이 상자를 통과 | 같은 식으로 사건 기록, 판이 실제로 상자를 침 → 같은 사건 뒤 상자 경로가 다름 | 사건 같음, 결과 다름 |
| r12 | FLOW-QUEUE | 식 | 같은 식. M 에서는 실제 접촉 · 회전 · 나란히 붙은 상자에서도 발생 | 사건 조건 같음 |
| r13 | 수거(route 1 → 4) | 수거기 운동학, 해제 거리까지 슈트 장애물 | 같은 운동학, 해제 거리까지 슈트 자세에 붙잡은 뒤 비활성 | 같음 |
| r14 | PUSH_MISSED · 센서 판정 코드 · HMI 계수 | 코어 | 같은 코드 | 같음 |
| r15 | PART_DROP(셀 A) | 데크 끝 규칙 | 같은 규칙(1차) + 옆으로 떨어짐(보조, y 기준) | 같음(+보조) |
| r16 | 바닥으로 떨어짐(셀 B) | 일어날 수 없음, 규칙 없음 | 일어날 수 있음, 사건 규칙 없음(`on_floor` 보고만) — 떨어진 상자는 route 0 으로 남는다 | 다름 |
| r17 | 상자 쌓임(올라탐) | 일어날 수 없음 | 일어날 수 있음(`stacked` 보고만). 센서는 높이 \|y\| ≤ h/2 + 빔/2 로 보므로 올라탄 상자를 놓칠 수 있다 | 다름 |
| r18 | 셀 A 가이드 · 바닥 마찰 | — | 정적 면 계수 0 + 최댓값 결합이라 가이드 · 바닥 마찰도 상자 계수(셀 B 는 `wall_friction` 0) | 가정 |
| r19 | 바닥 높이 | 0 | 0 | 같음 |
| r20 | 마찰 배율 `friction_scale` | 읽지 않음(F 응답 바이트 불변, 시험) | 셀 A: 부품 재질 마찰. 셀 B: 정적 면 · 판 · 상자끼리의 미끄럼 마찰과 슈트 x 힘의 목표(chute_x_mu)를 함께 곱함. 비틀림 · 구름 마찰은 그대로. 기본 1 | 감도 전용 |
| r21 | 부품 초기 측면 위치(배치 transform z) | 셀 B: `<part>.initial_z` 로 읽음. 셀 A: 0 고정 | 셀 B: 같은 값을 부품 시작 위치로. 셀 A: 0 이 아니면 적재 거부 | 셀 B 같음 · 셀 A 모형 없음 |

### 3-3. 래더와 상수의 출처

- **셀 A 정답 래더**: plc-twin-lab `ladders/cell-a/correct/program.ldprog.json`(sha256 `5058bd0b97644e66c0310a540a0403931bf6bd8195445576430d6dd1cabf8ef1`, 27 렁, 3j 이후 변경 없음, TR-2026-02 · 03 · 04 와 같은 파일). 10 스캔 센서 필터 · 25 스캔 반전 정지 · 왕복 3회. **이 상수의 교정 출처는 문서에 없다.** 이 브랜치의 셀 A 태그 맵으로 F · M0 모두 실행됨을 개발 실행에서 확인했다(§4).
- **셀 B 정답 래더**: MuJoCo 모드가 받는 표준 셀 B(asm-pusher 1.5.0, 3h/3i 논리)에 맞는 **3i 래더** — plc-twin-lab `fe605e1:ladders/cell-b/correct/program.ldprog.json`(sha256 `eb44ce59b386e175ab22255f684dbd277b27e00906fb0b92d81703e7f389209f`, 788 렁), `generate_3i.py sorting()` 이 만든 것.
- **「셀 B(3i)」라는 이름.** 이 편에서 셀 B 는 **셀 B(3i)** 로 적는다. TR-2026-02 · 03 · 04 가 「셀 B」라 부른 것은 그 뒤 판인 3k 셀(누적 고속 카운터 위치 규칙이 있는 asm-pusher 1.6.0, 정답 래더 569 렁 `05999e23…`)이다. 셀 B(3i)는 그보다 앞선 1.5.0 설계와 3i 래더(788 렁)로, 셀 설계 · 정답 래더 · 음성 래더 셋 · 실행 플랫폼(리눅스 대 macOS)이 모두 다르다. 같은 것은 셀 A 정답 · 음성 래더 파일뿐이다. 3k 셀은 MuJoCo 모드가 거부한다(D1, §11).
- **셀 B(3i) 상수**(`generate_3i.py` 의 상수, `cells/3i-parameters.json` = asm-pusher 1.5.0 `cell_design` 사본): 슈트 가득 ≥ 45 스캔(`full_hold_s` 0.45) → FaultCode 3 · 출력 가득 ≥ 100 스캔 → 4 · 도착 센서 ON > 29 스캔(`arrival_on_limit_s`) → 5 · 행정 시간 초과 > 31 스캔(`pusher_timeout_s`) → 14 · 슈트 확인 창 165~235 스캔(`chute_confirm_delay_s` 2.0 ± 0.35) · 양품 출력 창 198~269(`out_confirm_delay_s` 2.333 ± 0.35) → 13 · 최소 간격 62 · 무공급 정지 3000 · 복구 상수 · **발사 지연 계산식 `Delay = ⌊PulseSpan × 232 / (i × 50)⌋ − 7` 스캔**(계수 232 = (`fall_delay_s` 0.152 + `fire_lag_s` 0.08) × 1000 의 고정 소수점 표기, 펄스 간격으로 벨트 속도를 반영 — `generate_3i.py` 44~46행).
- **확인 창의 기준점**(`generate_3i.py sorting()` 판독): 도착 판정 `Arrive`(필터된 atStopper 상승, 운전 중, 2 스캔 필터) 때 불량 상자는 그 스캔 번호를 `ExpectChute` 대기열에, 양품은 `ExpectOut` 에 넣는다. 정상 모드에서 필터된 슈트 센서 `Chute`(2 스캔 필터)가 오를 때 나이 = 현재 스캔 − `ExpectChute` 맨 앞이 165~235 여야 하고, 아니면(또는 기다리는 중 235 초과) FaultCode 13. 양품 출력 창도 같은 방식으로 `Arrive` 부터 필터된 Out 상승까지 잰다.
- **상수의 출처 기록**(asm-pusher 1.5.0 `cell_design` provenance 직접 확인, 모두 [가정] 등급):
  - `chute_confirm_delay_s` 「원호 · 경사 지지 위의 계산 이동 이력으로 맞춘 슈트 센서 도착 창. 실물 실측이 아니다」 — 모형 이력 출처.
  - `full_hold_s` 「정상 상자의 센서 ON 폭 + 필터 지연보다 길게」 — 모형 이력 출처(정상 ON 폭, 하한 규칙).
  - `pusher_timeout_s` 「정상 전진단 0.29 s + 스캔 여유」 — 실린더 궤적 출처(두 모형이 같은 코어).
  - `fall_delay_s` 0.152 · `fall_detect_latency_s` 0.0126 · `fire_lag_s` — 발사 지연. 0.142 → 0.152 s 는 빠른 플랜트 쓸기에서 벨트 0.97 배 때 첫 상자가 −0.2309 m 위치에서 일찍 닿아 바꿨다(plc-devices `phase3i.md` 31~38 · 90~99). `fall_detect_latency_s` 는 실행 중 아무도 읽지 않는 설계 상수로, `tests/check_phase3e_geometry.py` 에서 발사 지연 0.152(허용 5 ms)를 정하는 데만 쓰이고(「명목 이력 첫 접촉으로 교정」) 래더에는 계수 232 로만 들어간다 — 모형 이력 출처.
  - `out_confirm_delay_s` 「분류 위치에서 출구 센서까지 거리/벨트속도로 계산한 도착 창의 중심」 — 닫힌 식.
  - `arrival_on_limit_s` 「3h 복귀 · 편차 · 압력차 · 안내 치수 시험 가정. 식과 실행 계약으로 확인하고 현물 보증에 사용하지 않음」 — 모형 이력 아님.
  - 셀 B 3f 도착 지연은 `design_3f.py` 닫힌 식(42 스캔).
  - **상수를 플랜트에 맞춰 정하는 끝에서 끝까지의 절차는 어디에도 문서로 없다.** 그래서 조건 M1 의 「같은 교정 절차」는 문서에 남은 통계와 기준을 MuJoCo 에서 다시 재는 규칙으로 이 편이 정의한다(§6-1).

### 3-4. 음성 래더 (알려진 결함)

| 셀 | 래더 | sha256 | 결함 | 기대 사유 |
| --- | --- | --- | --- | --- |
| A | `late-reverse` | `76018c387dddc09aa5411da241897c1ba20a4629844c301ccd3200140f1b7aa1` | 반전을 150 스캔 늦게 | `PART_DROP` |
| A | `swapped-sensors` | `7fd10917b31949e24528fbc5398501cdd9852cda18537af07671c0d308e8c6e5` | 좌우 센서 뒤바꿈 | `PART_DROP` |
| B(3i) | `push-timing-off` | `78951c5517af831727f5518d5d31b0ad9a702ff0feb605b45a590afe829f4010` | 발사 +50 스캔 | 물리 사건에 `PUSH_TOO_EARLY` · `PUSH_TOO_LATE` · `PUSH_MISSED` 가운데 하나 이상. **「미완료」는 기대 사유가 아니다** — 1,800 틱 실행은 생산 완료(개발 시드에서 약 틱 4,461)에 닿지 않아 결함과 무관하게 항상 미완료다 |
| B(3i) | `ignore-curtain` | `396aa80ffa273e6d0374ffd8a99c1eb619a5224a7ef7d8338c70961cd98e2d7d` | 커튼 무시 | 다리 판정 `PLC_CURTAIN_IGNORED` |
| B(3i) | `no-sort-check` | `22ccda36321cdbd4b9bd1c651deab467157ecfe88347d0ed9a3e515b035724dc` | 분류 확인 없음 | criteria-3i 는 `SORT_CHECK_MISSING` 을 적었으나 3i 의 앱 · 다리 어디에도 이 사유를 내는 곳이 없다 |

- 셀 B(3i) 음성 래더 셋은 plc-twin-lab `fe605e1` 에 있다. 3j/3k 전용 음성은 범위 밖이다.
- **`no-sort-check` 는 어느 모형에서도 「기대 사유 검출」이 될 수 없다.** macOS 3i 최종 검증 · 리눅스 F 게이트 · M0 개발 실행 모두 사건 0 · 다리 판정 0 · FaultCode 15 로 [FAIL] 이었다. 그래서 주 지표에서 빼고 판정 [FAIL] 만 세는 보조 지표에만 넣는다(L2, §7).
- 빠른 모형의 기대 사유 검출은 5종 중 4종으로 이미 알려져 있다(macOS · 리눅스 F 게이트 같음, §4).

### 3-5. 판정 계산 (`고정입력_TR-05/bridge/run.py`, plc-twin-lab 다리와 같은 식)

- **공정 판정 [PASS]** = 완료 ∧ 물리 사건 0(생산 사건 PART_PACKED · REJECT_COLLECTED 제외, PART_COLLECTED 등 중립 사건 제외) ∧ 다리 판정 0.
- 완료: 셀 A = 방문 `['right','left'] × 3` ∧ 탐침 `Rounds == 3` ∧ 끝 Q 모두 꺼짐. 셀 B = 부품 20개 모두 맞는 경로(불량 → route 1 또는 3, 양품 → route 2) ∧ `Arrivals == 20`.
- **시나리오별 판정과 틱 수**(실행기 인자 `--ticks` 로 고정, `summary.json` 의 `ticks` 가 다르면 `[INVALID]`):

| 셀 | 래더 | 시나리오 | 틱 | 판정 |
| --- | --- | --- | --- | --- |
| A | 3종 | `normal` · `cycle-stop`(pb1 틱 600) | 1,000 · 1,200 | 공정 판정 |
| B | 정답 | `normal` | 5,000 | 공정 판정 |
| B | 정답 | `curtain` | 1,000 | **안전 판정**: 커튼 감지가 있음 ∧ 감지 직전 틱의 `B.Conv.run` 켜짐 ∧ 커튼 ON 인 모든 틱에서 다음 Q 의 `B.Conv.run` · `B.Psh.sol` 꺼짐 ∧ 감지부터 벨트 · 푸셔 속도 0 까지 ≤ 0.265 s ∧ 물리 사건 0. 완료 · 다리 판정은 보지 않는다 |
| B | 정답 | `recovery` | 2,800 | 다리의 복구 검사 상태 |
| B | `push-timing-off` | `normal` | 1,800 | 공정 판정(길이상 완료 불가 → [FAIL] 자명) |
| B | `ignore-curtain` | `curtain` | 500 | 공정 판정(다리 판정 `PLC_CURTAIN_IGNORED` 포함) |
| B | `no-sort-check` | `flow` | 800 | 공정 판정(길이상 완료 불가 → [FAIL] 자명) |

- **장부 무관 판정**(보고용, 셀 B 공정 판정에만): 완료 조건의 「양품 → route 2」를 「양품 → route 2, 또는 route 0 이면서 그 상자의 x 가 out 센서 위치(셀 배치 `out_x` 2.2 m)를 넘었고 `on_floor` 가 아님」으로 바꾼 판정. M 은 `state.physics.parts[]` 의 x · `on_floor`, F 는 `state.parts` 의 x 를 쓰고 `on_floor` 는 거짓(F 에는 바닥 낙하가 없다). 나머지는 공정 판정과 같다. 원인 분류 (다)(§7)를 확인하는 데 쓴다.
- 다리 판정: `PLC_CURTAIN_IGNORED`(커튼 시나리오, 감지 뒤 0.265 s 안에 정지하지 않음).
- 래더의 잠금 사유는 `probes.FaultCode` 로 남는다. 실행기는 **첫 잠금의 틱과 FaultCode** 를 따로 기록한다(끝 FaultCode 는 첫 잠금 뒤 바뀔 수 있다).
- **참조 일치**: 정답 래더는 스캔마다 참조 논리와 같은 입력에서 내는 Q 가 같아야 한다(`reference-10ms-differences.json`). 참조 논리는 조건마다 다르다 — F · M0 = extctl `native/tests/external_control/logic.py`(셀 A `Logic`, 셀 B `Logic(True)` = SafeguardLogic, fe605e1 다리와 같음, 원래 상수), **M1 = 같은 `logic.py`(sha256 기록)에 §6-1 의 새 상수를 매개변수표로 넣은 「M1 참조 논리」**(바꾼 상수만 표에 넣고 나머지는 원래 값). `logic.py` 는 창 · 한도를 실수(초)로 비교하므로(\|clock·DT − 큐 − delay\| > tol 등) 정수 스캔 상수를 **반 스캔 안쪽 여유**로 적는다(결정 (d)): 슈트 확인 창 [lo, hi] → `chute_confirm_delay_s` = (lo + hi)/2 × 0.01, `chute_confirm_tolerance_s` = ((hi − lo)/2 + 0.25) × 0.01. 슈트 가득 N 스캔 → `full_hold_s` = (N − 0.5) × 0.01. 발사 지연 뺄셈 상수 7 → 7 − n → `fall_delay_s` 에 n × 0.01 을 더하고 `fire_lag_s` 에서 n × 0.01 을 뺀다(합 0.232 = 계수 232 그대로). 이 표기가 모든 나이 · 모든 스캔 수에서 래더의 정수 판정과 같음을 실행기 자기 시험이 확인한다(여유 없이 적으면 원래 2.0 ± 0.35 도 경계 나이에서 정수 창과 어긋나는 점이 있다). 무효 판정에 쓰는 범위는 그 실행의 틱 0 부터 첫 잠금(FaultCode 걸림) 전까지이고, §8 ② 의 예외 모양 하나를 뺀다. 첫 잠금 뒤 차이는 태그별로 보고만 한다. 이 범위는 개발 실행에서 잠금 뒤 램프 차이(§4)를 본 뒤에 정했다(L1).

## 4. 예비 관찰 (이미 본 것 — 확인 실험의 근거로만 쓴다)

**아래 수치는 이 사전 등록 전에 이미 본 결과다. 공식 실행(§5)의 결과와 한 표로 합치지 않는다.** 예측 P1 · P7 은 이 관찰을 보고 세운 **재현 예측**이다(§7). 셀 A 정답 래더의 M0 결과는 공식 입력과 같은 입력에서 이미 봤으므로 예측하지 않고 탐색 보고 E6 으로만 둔다(§5-1, L3).

공통 조건: `feature/tr05-e2`(E2-1 · E2-2 는 `ab5d3c9` 와 같은 내용, E2-3 은 `0edb740` 과 같은 내용), 우분투 PC(linux-arm64, Ubuntu 24.04.5, Clang 21.1.8, Release, `-ffp-contract=off`), MuJoCo 3.12.0(libmujoco sha256 `ddc46a81d9acfdd3afec7ac4723350a1a5e21ac5ce774ab7e904921f20c3a36d`). 공식 · 교정 시드는 한 번도 뽑거나 적재하거나 돌리지 않았다. 쓴 시드는 이미 본 1 · 2 · 3 뿐이다(구현 단계는 §4-3).

### 4-1. 단위 시험(ctest, 래더 없음 · 내장 제어기 또는 고정 명령)

| 관찰 | 입력 | 값 |
| --- | --- | --- |
| 셀 A 결정성 | 왕복 시험 패턴 2,500 틱 | 두 새 플랜트의 틱별 해시 2,500/2,500 같음, 반전 59회 |
| 셀 A 열린 고리 | 같은 명령 36 틱 | F 와 M 의 x 차이 최대 2.4 mm |
| 셀 A 열린 끝 낙하 | 벨트를 열린 끝으로 | PART_DROP 틱 F 30 · M 30(차이 0) |
| 셀 B 결정성 | 시드 1, 불량률 0.2(불량 5개), 4,000 틱, pb3 틱 5 · pb0 틱 30 · `collector.chute` 틱 1800 부터 | 4,000/4,000 같음 |
| 셀 B 열린 고리(F 의 Q · 자극을 M 에 재생) | 같은 입력 | 최종 경로 20/20 같음(슈트 5 · 출력 15). 상승 에지 차이(M − F, ms): atStopper 평균 3 · 최대 10, out 3.3 · 10, isBad 6 · 10, 슈트 센서 164 · 390(짝 5개). 수거 끝이 F 보다 23~137 틱 늦음. 기울기 표시 첫 틱 257 |
| 셀 B 내장 제어기(3h/3i 논리) 연결 실행 | 같은 입력 | F 는 끝까지 운전, M 은 틱 1710 에 chute-full 로 정지. 원인: 이송 중 상자가 최대 약 120° 돌아 다섯째 상자의 경사 방향 위치가 F 1.706 m · M 1.520 m(M 에서 0.186 m 위쪽, 대기열이 그만큼 길어짐)가 되어 센서 띠(±0.0765 m) 안에 멈춤 |
| 셀 B `chute.jam` | 시드 1, 틱 1000 부터 2,500 틱 | 슈트 센서 상승 F 3 · M 3, CHUTE-01 · PUSH-RETURN 사건 같은 틱, PLC `SORT_TRACKING_LOST` F 1회(틱 1158) · M 0회 |
| `friction_scale` | F 0.7 대 기본 | 응답 바이트 같음(셀 A 1,000 틱 · 셀 B 2,500 틱). M 에서는 셀 A ×0.5 최대 \|dx\| 0.302 m · 셀 B ×0.7 0.051 m |
| 벨트 배율 | 0.95 · 1.00 · 1.05, F · M, 셀 A · B | 벨트 최고 속도와 부품 속도 비가 배율과 같음 |
| 슈트 가득의 여유(계산) | F 큐 | F 의 다섯째 상자 중심은 센서 띠 중심에서 0.221 m(띠 가장자리 밖 0.1445 m) — 4 간격에 간격당 0.036 m 여유. 상자가 평균 약 10° 돌면 다섯째 상자가 띠 안에 들어와 슈트 가득이 된다 |

### 4-2. 다리 · 래더 개발 실행(E2-3, 2026-10-08 — 래더를 플랜트에 붙인 실행)

| 실행 | F | M0 |
| --- | --- | --- |
| F 게이트(셀 A 시드 1, 셀 B 시드 1 · 2 · 3, 각 2회) | macOS `3i-final-2` 와 항목마다 같음: 셀 A 정답 [PASS] ×2 · 참조 차이 0 · 3회 왕복. 셀 B 정답 [PASS] ×2(시드별 결정적), 부품별 분류 = `plc-devices-3i-4a-seed-results.json`(출력/슈트 15/5 · 17/3 · 17/3), 참조 차이 시드마다 1 스캔(틱 4461, B.Conv.run · B.Lamp.green · B.Lamp.yellow — §8 ② 의 예외 모양). 음성: swapped-sensors · late-reverse PART_DROP, push-timing-off JAM · PUSH_MISSED · PUSH_TOO_EARLY FaultCode 13, ignore-curtain PLC_CURTAIN_IGNORED FaultCode 11 — 검출. no-sort-check [FAIL](사건 0 · 판정 0 · FaultCode 15). curtain(500 틱) 감지 237 · 정지 257(0.20 s) [PASS]. recovery [PASS](PUSH_TOO_EARLY FLY-01 part2 틱 659) | — |
| 셀 A 정답 `normal` 1,000 | [PASS](게이트) | [PASS] ×2, 같은 기록 해시 `71c4f822…` |
| 셀 A 정답 `cycle-stop` 1,200 | (게이트 대상 아님) | [PASS] ×2, 같은 기록 해시 `f597ade4…` |
| 셀 A 음성 2종 | 게이트에서 검출(`normal`) | 보지 않음 |
| 셀 B 정답 `normal` 시드 1, 5,000 | [PASS] | [FAIL] ×2, 같은 해시 `fc4aa4a4…` — 틱 1710 첫 잠금 FaultCode 3(슈트 가득, 내장 제어기와 같은 틱), Arrivals 20 · ChuteArrivals 5 · OutArrivals 15, 부품 18 · 19 route 0, 물리 사건 0, `values_sha256` `de267219…`, 판 추종 최대 2.5e-5 m, tilt_flag 켜짐, `run_max_yaw_rad` 0.049(데크 위 상자만). 참조 차이 3,291 스캔 — 모두 틱 1710 부터 끝까지 B.Lamp.red/B.Lamp.yellow(래더는 Latch ∧ Recovery ≤ 1 이면 적색, 참조는 황색) |
| 셀 B 정답 `curtain` 시드 1, 1,000 | [PASS] 감지 237 · 정지 257 | [PASS] ×2(결정적) 감지 237 · 정지 257(0.20 s ≤ 0.265), 명령 모두 꺼짐, 사건 0, 이후 FaultCode 18(작업이 남은 채 정지) — F 와 같은 수치 |
| 셀 B `ignore-curtain` 시드 1, 500 | 검출(PLC_CURTAIN_IGNORED) | [FAIL], PLC_CURTAIN_IGNORED 2건(검출) |
| 셀 B `push-timing-off` 시드 1, 1,800 | JAM PUSH-RETURN · PUSH_MISSED FLY-02 · PUSH_TOO_EARLY FLY-SIDE, FaultCode 13 | 같음(1회) |
| 셀 B 정답 `recovery` 시드 1, 2,800 | [PASS](PUSH_TOO_EARLY FLY-01) | [PASS](PUSH_TOO_EARLY FLY-01, 1회) |
| 셀 B `no-sort-check` `flow` 시드 1, 800 | FaultCode 15, 사건 0 | FaultCode 15, 사건 0(1회) |
| 플랜트 오류 | — | M 실행 어디에도 없음 |

**실행 시간(실측, 실행 1회, 앱 시작 · 적재 · 래더 엔진 · 다리 포함)**: F 셀 A `normal` 0.8~1.1 s, 셀 B `normal` 7.7~11.4 s(틱당 1.5~2.3 ms) / M 셀 A 1.1~1.6 s, 셀 B `normal` 24.6~26.1 s(틱당 4.9~5.2 ms; 끝까지 분류하는 배치는 34 s 안팎 예상), `recovery` 18.8 s(틱당 6.7 ms), `curtain` 1,000 틱 4.4~5.9 s.

**이 관찰을 본 뒤 정한 것.** 시드 1 은 공식 입력에서 뺀다. 공식 배치는 새 시드로 뽑고(§5), 불량 개수(입력의 성질)로 묶음을 나눈다 — 슈트 가득이 불량 5개에서 나타났기 때문이다. 감도 항목 셋(transition_mu · wall_friction · chute_x_mu 힘)은 개발 단계 코드 검토가 이 관찰을 보고 권했다. 참조 일치 무효 범위(§3-5 · §8 ②)는 위 셀 B M0 의 잠금 뒤 램프 차이를 본 뒤 정했다. `no-sort-check` 를 주 지표에서 뺀 것(§3-4)은 위 기록을 본 뒤 정했다. 모형 가정 설정(§6-4)과 원인 분류(§7)는 v0.4 교차 검토가 위 기전을 보고 권했다.

### 4-3. 구현 단계에서 본 것(E2-4 앱 · E2-5 실행기, 2026-10-08 — 모두 시드 1, 등록 전에 본 것)

공식 · 교정 시드는 이 단계에서도 뽑거나 적재하거나 돌리지 않았다(시드 표 자기 시험은 접두 `TR-2026-05/selftest-a·b·c/` 만). 래더를 붙인 실행은 시드 1 의 §4-2 와 같은 입력뿐이다. 셀 A 음성의 M0(P5 대상), 시드 2 · 3 의 M0, 감도 · 모형 가정 설정 실행, E4 의 M0, 교정 · M1 재생성 · 개발 시드 끝까지 실행은 하지 않았다(감도 설정은 적재만).

| 관찰 | 입력 | 값 |
| --- | --- | --- |
| 기본 불변 비교(래더 없음, 내장 제어기 · 고정 명령) | 시드 1: F 셀 B 연결 실행 4,000 틱, 그 명령의 M 재생 4,000 틱, M 셀 B 연결 실행 2,000 틱, 셀 A F · M 1,000 틱, `0edb740` 빌드와 대조 | F 응답 바이트 같음(셀 A 1,000 · 셀 B 4,000), M 적분 상태 · 기존 키 틱마다 같음. 새 키(`parts` · `first_contact`)와 값 목록 · 해시 · 규칙 문자열만 다름 |
| 첫 판-상자 접촉 | 시드 1 F 연결 명령을 M 에 재생, 1,600 틱 | 밀린 5개(part1 · 9 · 10 · 14 · 20) 모두 F · M 같은 틱(236 · 769 · 836 · 1102 · 1502) · ms 1, 포착 틱(258 · 791 · 858 · 1124 · 1524)보다 앞. x 는 M −0.205 ~ −0.213, F −0.200 ~ −0.208 — 다섯 상자 모두 M − F = −4.8 mm. 같은 차이가 틱 100 부터 있다(벨트 기동 때 미끄럼으로 생긴 위치 지연). §6-1 규칙을 이 값에 그대로 대면 뺄셈 상수가 7 → 6 이 된다 — **M1 상수는 동결 뒤 교정 실행으로만 정하고 시드 1 값으로 정하지 않는다**(결정 (f)) |
| 슈트 x 힘 | 시드 1 연결 실행 600 틱 | 데크를 벗어난 part1 의 x 감속: `chute_x_force=1` 8.20 m/s²(빠른 규칙 8.34), 0 이면 0.92 m/s² |
| 센서 회전 윤곽 | 시드 1 열린 고리 450 틱, `sensor_footprint_rotated` 0 · 1 | chuteSensor 물리 표적이 켜진 틱 11 · 19(8 틱 다름), inspection · atStopper · out 450/450 같음 |
| 부품별 지지면 | 시드 1 M 2,000 틱 | 동적 상자 표본 deck 34,570 · arc 586 · slope 4,664 · floor 0, stacked 0. 원호 gap 중앙값 −0.23 mm, 경사면 −0.013 mm |
| 측면 위치 | 시드 1 part1 z +5 mm, 적재 · 100 틱 | 적재 · 틱 40 에 F · M 모두 0.005, 틱 100 에 깔때기로 F 0.0015 · M 0.0025. values 해시만 바뀜. 셀 A 오프셋은 거부 |
| 개발 회차(래더 연결) | 시드 1 · F · M0, 단계 주 실행 · 반복 · 게이트 · 열린 고리, 38 실행(10회 규칙 시험용 인위 주입 포함) | 38/38 `[VALID]`. M0 정답 `normal` = 원인 분류 (가) · 첫 잠금 FaultCode 3 · 첫 갈라짐 틱 1710 · r5. 열린 고리 P7 계수 40/40, 슈트 짝지은 상승 차이 중앙값 +170 ms. 표 · 공개본 표 · 독립 검산의 판정 차이 0, 공개본 문자열 검사 0 건. 개발 표의 예측 값(배치 하나라 예측 판정으로 의미 없음): P1 [틀림](묶음 5 배치 1개), P6 [틀림](인위 주입), P7 [맞음], 그 밖 [판정 불가] · [틀림] |
| 10회 규칙 시험 | 시드 1 정답 `curtain`, 2회째 Q 한 틱을 일부러 뒤집음 | 비결정 쌍으로 잡혀 10회로 늘고 [PASS] 10/10 |
| 참조 일치 | F 게이트 기록 시드 1 · 2 · 3, 시드 1 M0 | F: 예외 모양 정확히 1건(틱 4461), 그 밖 0. M0: 첫 잠금 1710 전 0 건 · 뒤 3,291 건(B.Lamp.red · yellow) |
| 교정 측정기 개발 시험(값은 쓰지 않음) | 시드 1 F 연결 · M0 열린 고리 기록 | F 불량 짝 5 · 지나간 구간 5. M0 열린 고리의 래더 첫 잠금 스캔 1717(FaultCode 3), 짝 5 는 모두 그 전에 잡힘(미측정 0), part20 의 띠 안 정지 구간(시작 틱 1665)은 통계에서 빠지고 보고됨 |
| 특허 대조(v0.5 를 넣고 실행) | v0.5 · 실행기 · 래더 공개본 · 개발 공개본 묶음 | 5건, 모두 §13-1 의 구성 대조 부정문 한 줄 · 그 밖 0(§13-1) |

### 4-4. 동결 뒤에 본 개발 관찰 (동결 커밋 `3a12187` 뒤 · 공식 실행 전 — 예측을 바꾸는 근거로 쓰지 않는다)

공식 시드는 시드 표를 만들려고 적재만 했다. 원본 기록은 `~/tr05-run/calib-1/`(gate · calib · pc2 · pc2-a1), 요약 · 해시는 `TR공개/실행/tr05-calib-1/`(`sha256.txt` 189 파일 · `traces-sha256.txt` 68 기록).

**양성 대조 1(§8, 공식 빌드)** — 개정 1 전(`gate`) · 뒤(`gate-a1`) 모두 31 검사 가운데 30 [PASS], §8 기준 통과.

| 항목 | 값 |
| --- | --- |
| 회귀 시험 | ctest 11/11(같은 실행 파일, 「동결 뒤 변경」 6행) |
| 셀 A 시드 1 | [PASS] ×2, 결정적(기록 해시 `d753e4ab…`), 참조 차이 0, 첫 잠금 없음, 왕복 3회, 제어 연결 실행의 참조 기록 차이 55 틱(macOS 와 같음) |
| 셀 B 시드 1 · 2 · 3 | [PASS] ×2, 결정적(`f9aab67c…` · `d97114c0…` · `4c105404…`), 참조 차이는 시드마다 예외 모양 1건(틱 4461)뿐, 첫 잠금 없음, 부품별 분류 = `plc-devices-3i-4a-seed-results.json`(출력/슈트 15/5 · 17/3 · 17/3), 제어 연결 실행의 차이 2 틱 |
| 음성 | swapped-sensors · late-reverse PART_DROP. push-timing-off JAM · PUSH_MISSED · PUSH_TOO_EARLY, FaultCode 13(첫 잠금 427). ignore-curtain PLC_CURTAIN_IGNORED, FaultCode 11(239). no-sort-check [FAIL](사건 0 · 판정 0 · FaultCode 15, 첫 잠금 241) — 게이트의 「no-sort-check 검출」 한 항목만 [FAIL] 이며 이는 3i 에 기대 사유가 없어서다(§3-4 · L2). §8 의 기준은 「no-sort-check [FAIL]」이라 충족 |
| 커튼 · 복귀 | 커튼(500 틱, fe605e1 검사) 감지 237 · 정지 257(0.20 s) [PASS], 복귀 [PASS](PUSH_TOO_EARLY FLY-01 part2 틱 659). 모두 macOS `3i-final-2` 와 같음 |

**교정 실행(§6-1)** — 교정 시드 6개(묶음 3: 1865575037 · 4002380191, 4: 2948004803 · 3127217929, 5: 1050778556 · 983796061)의 F 정답 래더 `normal` 5,000 틱(벨트 1.00, `--report-first-contact`) 6/6 [PASS], 건너뛴 시드 0. 그 요청을 M0 에 재생 6/6, 경로 20/20. F 기록 해시 `bbc5020d…` · `b500ae7a…` · `9343cce4…` · `f362fadc…` · `82c143c9…` · `c48e867b…`. 교정 실행 수 12(F 연결 6 + M0 열린 고리 6).

| 상수 | 통계 | 새 값 |
| --- | --- | --- |
| 슈트 확인 창 165~235 | 나이 F [195, 196] · M [197, 234], m_lo 30 · m_hi 39, 중앙값 차 Δ +38 스캔, 창 폭 +36, 원래 창 밖 M 상자 0(M 최대 234 — 끝에서 1 스캔 안), 짝 F 24 · M 24, 래더 첫 잠금 0 · 미측정 0 · 짝 없는 Arrive 0 | **167~273** |
| 슈트 가득 45 | 지나간 구간 최대 F 11 · M 12 스캔, 빠진 구간 0 | **⌈45 × 12/11⌉ = 50**(상한 90 안) |
| 발사 지연 뺄셈 상수 7 | Δx = −0.004818 m(중앙값 F −0.20420 · M −0.20902 m, 24/24 상자) — 밀기 전 위치 지연 포함(결정 (f)) | **7 − ⌈0.004818/0.012⌉ = 6** |
| 바꾸지 않는 상수(보고만) | 양품 창 198~269: F · M 233~234(끝 3 스캔 밖). 도착 ON 최대 19(한도 29). 출력 ON 최대 19(한도 100) | 그대로 |

M1 래더 4개는 원래 래더와 상수 리터럴 줄만 다르다(36 · 36 · 36 · 33 줄, 그 밖 0). `push-timing-off` 의 +50 은 그대로. M1 참조 매개변수: `chute_confirm_delay_s` 2.2 · tolerance 0.5325 · `full_hold_s` 0.495 · `fall_delay_s` 0.162 · `fire_lag_s` 0.07.

**양성 대조 2 첫 실행 — 무효(보존)**: 개발 시드 18032821(묶음 3) · 2981378262(4) · 2617252722(5)의 셀 B 정답 `normal`, F · M0 · M1 9 실행, 모두 실행 범주 [VALID]. F 3/3 [PASS], M0 앞 둘 [PASS] · 2617252722 **[FAIL]**(첫 잠금 FaultCode 13 틱 1697 — 다섯째 불량 상자(Arrive 스캔 1461)가 슈트 센서에 닿지 않아 슈트 확인 대기 초과), M1 3/3 [PASS]. M0 2617252722 에서 첫 잠금 전 참조 차이 1건(틱 1696, B.Conv.run · Lamp.green · Lamp.red — 원래 참조 논리가 실수 비교로 한 스캔 먼저 잠금)이 나 §8 ② 로 회차 전체가 무효가 되었고, 실행기가 폴더를 `~/tr05-run/calib-1/pc2/_invalid/20261008T135111_참조-일치/` 로 옮겼다(지우지 않음, 사본 `실행/tr05-calib-1/pc2/`). 이 회차의 표 · 독립 검산 · 공개본 변환은 하지 않았다. → 개정 1.

**양성 대조 2 재실행(개정 1 뒤, 새 폴더 `pc2-a1`)** — 같은 명령, 9/9 [VALID], 회차 유효(실행 전체 무효 없음).

| 시드(묶음) | F | M0 | M1 |
| --- | --- | --- | --- |
| 18032821(3) | [PASS] | [PASS] | [PASS] |
| 2981378262(4) | [PASS] | [PASS] | [PASS] |
| 2617252722(5) | [PASS] | [FAIL] 첫 잠금 FaultCode 13 틱 1697(슈트 창 시간 초과), 첫 잠금 전 참조 차이 0, 기록 해시 `cffa0859…`(무효 회차와 같아 결정적), 원인 분류 (가) · 첫 갈라짐 잠금 13(슈트 창) · E1 r3 | [PASS] |

- 참조 차이는 F · M0(앞 둘) · M1 모두 예외 모양 1건(틱 4461)뿐. 장부 무관 판정 9/9 [PASS]. 표 · 공개본 묶음(문자열 검사 0 건) · 독립 검산은 원 회차 표 · 공개본 표 어느 쪽과 대조해도 차이 0. 개발 예측 값은 배치 3개라 의미가 없다(P1 [틀림] · P2 [맞음] · F3 [맞음] · 그 밖 [판정 불가] · [틀림]).
- 참고: 이 개발 배치의 묶음 5 M0 뒤바뀜은 P1 이 예측한 FaultCode 3 이 아니라 FaultCode 13 이었다. 교정 열린 고리의 M 슈트 나이 최대 234 는 원래 창 끝(235) 바로 안이다. 이 관찰로 예측을 바꾸지 않는다.

## 5. 확인 실험의 입력 [동결]

### 5-1. 셀 A

- 시드 · 배치가 없다(부품 1개, 결정적 배치). 공식 입력은 다리의 래더 시나리오 `normal`(1,000 틱) · `cycle-stop`(1,200 틱, pb1 틱 600)이다.
- 셀 A 정답 래더의 M0 `normal` · `cycle-stop` 결과는 개발 실행에서 이미 봤다(둘 다 [PASS], §4-2). 셀 A 는 시드가 없어 이 입력이 공식 입력과 같다. 그래서 **셀 A 정답 래더의 결과(F · M0)는 확인 예측을 두지 않고 탐색 보고 E6 으로만 적는다**(L3). 공식 실행에서도 돌려 기록은 남긴다.
- 셀 A 음성 2종의 M0 결과는 보지 않았다(F `normal` 은 게이트에서 봤다). 확인 예측(P5)은 음성 2종에만 둔다.
- 셀 A 의 M1 은 M0 과 같다(재교정 상수 없음, §6-1) — 돌리지 않고 표에서 「M1 = M0(실행 없음)」으로 적는다.
- 래더: 정답 1 + 음성 2. 입력 2. (래더, 입력) 6쌍 — 확인 대상은 음성 4쌍.

### 5-2. 셀 B(3i) (표준 cell-b-sort, asm-pusher 1.5.0, 3i 래더)

- **공식 시드 뽑기(동결 뒤 · 실행 전에 고정)**: `seed_k = SHA-256(UTF-8("TR-2026-05/official/" + str(k)))` 의 첫 4바이트(빅 엔디언 uint32), k 는 1 부터 앞자리 0 없는 10진수. 시드 0 · 1 · 2 · 3(예비 · 기존 고정 표의 시드)은 건너뛴다. 각 시드의 불량 개수를 앱의 적재(`load`, 시드 생성기 `SeededParts`, 불량률 0.2 — 부품마다 `rng.next() < 0.2`)로 세고 — 플랜트를 한 틱도 돌리지 않는 적재만 한다(D17) — **불량 3 · 4 · 5 개 묶음마다 처음 4개**를 고른다(12 배치). 불량 6개 이상은 빼다(D6). k ≤ 1000 안에서 묶음을 채우지 못하면 시드 표를 만들지 않고 멈춘다. 시드 표에는 쓰지 않은 k 를 포함해 조사한 모든 k 의 (k, seed, 불량 개수)와 고른 시드의 부품 분류 · 설정별 `values_sha256` · `setup_sha256` 을 적는다. 표 바이트에는 시각 · 경로가 없다. 시드 표는 **동결 커밋(§14-6) 뒤에만** `seed_table.py build --frozen-commit <40자>` 로 만든다(40자 커밋이 없으면 생성기가 거부).
- **교정용 시드**(조건 M1)는 같은 규칙에 문자열 `"TR-2026-05/calib/"` 로 묶음마다 2개(6 배치). **개발용 시드**(실행기 시험 · 양성 대조 2)는 `"TR-2026-05/dev/"` 로 묶음마다 1개. 세 집합은 서로 겹치지 않는다(겹치면 뒤 집합에서 다음 k 로 넘어감).
- **실행기의 시드 수용**: 시드 0~3 밖의 시드는 `--dev-seed` 표시가 있거나, 공식 회차 명령이 §10 의 시드 표(sha256 일치)에서 그 시드를 읽은 경우에만 받는다. 공식 · 교정 시드는 `--dev-seed` 로 주지 않는다.
- 초기 측면 위치는 기본값(z = 0)만 쓴다(모형 가정 설정의 ±5 mm 제외, §6-4). \|z\| > 0.125 m 는 M 에서 초기 겹침으로 거부되므로 범위에서 뺀다.
- 시나리오와 (래더, 입력):

| 래더 | 시나리오(틱) | 입력 | 쌍 |
| --- | --- | --- | --- |
| 정답 | `normal`(5,000) | 공식 12 배치 | 12 |
| 정답 | `curtain`(1,000, 첫 B.Psh.sol 다음 틱부터 작업자 진입) | 공식 12 배치 | 12 |
| 정답 | `recovery`(3i 판 `recovery_stimuli(tick)`: 리셋 5 · 600, 시작 30 · 520 · 900 · 2750, 작업자 280~449, 격리 630, 원점 650~849, 해제 950 · 2700, `collector.chute` 650 부터, 2,800) | 묶음 5 의 첫 배치 | 1 |
| `push-timing-off` | `normal`(1,800) | 공식 12 배치 | 12 |
| `ignore-curtain` | `curtain`(500) | 공식 12 배치 | 12 |
| `no-sort-check` | `flow`(800, 3i 판: io-map 상수 `pusher.flow_restriction=True` 완전 유량 차단, 상자 배치 그대로) | 묶음 5 의 첫 배치 | 1 |

- 다리의 `normal` 시나리오에는 `collector.chute` 자극이 없다(수거하지 않음, D15). `recovery` · `no-sort-check` 는 묶음 5 배치이므로 M 에서는 슈트 가득과 겹칠 수 있다(§11).

### 5-3. 크기와 시간

- 주 실행: 조건 3개 × [셀 A 6쌍 + 셀 B 50쌍] = 168, 셀 A M1 6 을 빼면 **162**(F 56 · M0 56 · M1 50).
- 반복: M0 · M1 의 모든 쌍 2회째 106, F 게이트 2회째 9(§6-3).
- 열린 고리 재생 14, P8 감도 156(셀 B M 96 · 벨트 F 24, 셀 A M 24 · 벨트 F 12), 모형 가정 설정 10 × (f + 2)(f = M0 에서 뒤바뀐 셀 B `normal` 배치 수, §6-4), E4 100(25 변종 × 2 시나리오 × F · M0).
- 교정(동결 뒤, 공식 실행 전): F 정답 래더 연결 실행 6 + M 열린 고리 재생 6(건너뛴 교정 시드가 있으면 그만큼 더).
- 추정 시간(개발 실행 실측 기준, 순차): 주 실행 20~29분, M 반복 25~33분, 게이트 · 열린 고리 · 감도 · E4 약 55~75분, 모형 가정 설정 배치당 약 5분(스텝 0.0005 는 틱당 약 2배) → **합계 약 2.0~3.9 시간**(f 에 따라). 10회 규칙이 M0 에 걸리면 약 80~110분, M1 이면 약 78~109분 추가. 원시 기록(`trace.jsonl`, 셀 B 5,000 틱 F 36 MB · M 136 MB, `parts[]` 보고로 M 은 더 늘어남) 합계 40~60 GB 추정, 10회 규칙이 한 M 조건에 걸리면 약 25 GB 추가. 디스크 여유 632 GB. 병렬 실행 비용은 재지 않았다.
- 개발 중 오염 금지: 실행기 개발 · 시험은 개발 시드와 별도 출력 폴더로만 한다. 공식 시드의 실행은 공식 실행에서 처음 한다.

## 6. 설계 [동결]

### 6-1. 조건

| 조건 | 플랜트 | 래더 상수 | 참조 논리 |
| --- | --- | --- | --- |
| **F** 빠른 이송 | `--physics fast` | 원래(§3-3) | 원래 |
| **M0** MuJoCo 원래 상수 | `--physics mujoco`, 물리값 기본 목록 | 원래 | 원래 |
| **M1** MuJoCo 재교정 상수 | M0 과 같음 | 아래 규칙으로 MuJoCo 에서 다시 구한 상수로 다시 생성한 셀 B 래더(정답 + 같은 결함의 음성 3종) | M1 참조 논리(§3-5) |

**M1 의 재교정 규칙(이 편이 정의 — 원래 절차는 문서로 없다, §3-3).** 출처에 「모형의 계산 이력에서 정했다」고 적힌 상수만 다시 구한다. 교정용 6 배치에서 F 정답 래더 연결 실행(벨트 1.00)의 Q · 자극을 기록하고, 같은 요청을 M 플랜트에 열린 고리로 재생한다. F 의 통계는 F 연결 실행 기록에서, M 의 통계는 M 열린 고리 기록에서 같은 규칙으로 잰다.

| 상수 | 출처 | 통계(교정용 배치) | 새 값 |
| --- | --- | --- | --- |
| 슈트 확인 창 165~235 | 모형 이력 | 불량 상자마다 나이 = (그 상자에 짝지어진 필터된 `Chute` 상승 스캔) − (그 상자의 `Arrive` 스캔). F 범위 [a_F, b_F], M 범위 [a_M, b_M](최소 · 최대). 중앙값 차이 Δ 도 잰다 | 여유 m_lo = max(0, a_F − 165), m_hi = max(0, 235 − b_F)(원래 창이 F 관측 범위 밖으로 남긴 여유). **새 창 = [a_M − m_lo, b_M + m_hi]**(스캔 정수). 어느 모형이든 짝이 3개 미만이면 바꾸지 않는다. Δ · 창 폭 변화 · 원래 창 밖 상자 수를 함께 보고 |
| 슈트 가득 45 스캔 | 모형 이력(정상 ON 폭, 하한 규칙) | 슈트 센서(필터 전 `B.Sen.chute` 원신호) ON 구간 가운데 **지나간 구간**만: 상승과 하강이 모두 그 실행 안에 있고, 하강 순간 「그 상자」(하강 틱에 슈트 센서 z(1.503 m — F 기록의 띠 통과 중심)에 가장 가까운 슈트 부품, route 1 · 4)의 경사 방향 속도가 0.05 m/s 를 넘고(M: `parts[].slope_velocity_mps`, F: `state.parts` 의 vz ÷ cos 20°), 수거(route 4 로 바뀜)로 끝나지 않은 구간. 길이 = 1 ms 에지를 10 ms 스캔 경계로 올린 스캔 수. 최댓값을 F · M 각각 잰다. 지나가지 않은 구간(띠 안 정지 · 실행 끝 · 수거)은 빼고 그 수와 시작 틱을 보고 | **max(45, ⌈45 × (M 값 ÷ F 값)⌉)**. 상한 90 스캔 — 넘으면 「재교정 불가」로 적고 45 를 쓴다. F 값이 0 이거나 지나간 구간이 어느 모형이든 3개 미만이면 바꾸지 않는다. 이 상수를 줄이는 방향은 쓰지 않는다 |
| 발사 지연 식(계수 232 · 뺄셈 상수 7) | 모형 이력(쓸기 · 명목 첫 접촉) | 밀린 불량 상자마다 첫 판-상자 접촉 표본(§3-1 보고 ② — M `first_contact[]`, F `fast_first_contact`, 둘 다 플레이트 규칙이 밀기로 선택한 부품만, 선택 틱부터의 첫 접촉 표본)에서 그 상자의 중심 x(분류 위치 x = 0). Δx = 중앙값(x_M) − 중앙값(x_F). 원래 기준(3i 쓸기에서 첫 상자가 −0.2309 m 에서 「일찍 닿음」)과 같은 위치 기준이다 | 계수 232 는 그대로. **Δx < 0**(M 에서 상자가 덜 들어온 위치에서 판이 닿음 — 「일찍 닿음」 쪽)이면 뺄셈 상수 7 을 7 − ⌈\|Δx\| ÷ (1.2 m/s × 10 ms)⌉ 로 바꿔 발사를 그만큼 늦춘다. Δx ≥ 0 이면 바꾸지 않는다. **Δx 는 밀기 전 위치 지연(벨트 기동 때 상자 미끄럼 — MuJoCo 모형의 실제 효과)도 포함하며, 이는 의도한 것이다**(결정 (f) — 판이 닿는 순간 상자가 어디 있는가가 원래 기준이고, 그 위치가 늦은 까닭은 묻지 않는다). 상수는 동결 뒤 교정 실행으로만 정하고 시드 1 의 값(§4-3)으로 정하지 않는다. 속도 추정 전의 초기 Delay 16(⌊23.2⌋ − 7)은 재교정 대상이 아니다. 벨트 배율 쓸기는 교정에 쓰지 않는다(열린 고리 재생은 벨트 1.00 기록만 맞는다) |
| 양품 출력 창 198~269 | 닫힌 식(거리/벨트 속도) | 같은 방식으로 재서 보고만 | **바꾸지 않음**(D19). 교정에서 M 의 최댓값이 창 끝에서 3 스캔 안으로 들어오거나 M0 · M1 에서 FaultCode 13(out 창) · 4 가 나오면, 그 뒤바뀜은 「재교정 대상 밖 상수에서 생김」으로 따로 적는다 |
| 도착 센서 ON 한도 29 스캔 | 시험 가정 | atStopper ON 폭을 재서 보고만 | **바꾸지 않음**(D19). M 최댓값이 한도 3 스캔 안이거나 FaultCode 5 가 나오면 위와 같이 따로 적는다 |
| 출력 가득 100 스캔 | 출처 기록 없음 | out 센서 ON 폭 보고만 | 바꾸지 않음. FaultCode 4 는 위와 같이 따로 적는다 |
| 행정 시간 초과 31 스캔 | 실린더 궤적(같은 코어) | — | 바꾸지 않음(통계가 같음을 확인만) |
| 최소 간격 · 무공급 · 복구 상수 | 모형 이력 출처 기록 없음 | — | 바꾸지 않음 |
| 셀 A 상수 전부 | 출처 기록 없음 | — | 바꾸지 않음 → 셀 A 의 M1 = M0 |

**재교정 공통 규칙(모두 이 판에서 고정):**
- 래더 내부 신호(`Arrive` · 필터된 `Chute` · 필터된 Out)는 래더 엔진으로 잰다: 기록의 센서 이미지(스캔마다)를 원래 3i 정답 래더 엔진에 입력으로만 넣고(그 Q 는 버림) 탐침을 읽는다(`probe_engine.mjs` — 탐침과 겹치는 태그는 두 경로 값이 같아야 하며 다르면 멈춘다). 래더 밖에서 필터를 다시 구현하지 않는다.
- **측정은 그 기록에서 래더가 처음 잠그는 스캔까지만 한다**(결정 (e)): 잠금 뒤에는 Running 이 꺼져 `Arrive` 가 나오지 않는다. 그 뒤의 불량 · 양품 상자는 「미측정」으로 수를 보고하고(`unmeasured_after_lock`), 짝 수 규칙(3개 미만이면 바꾸지 않음)은 잰 짝으로 센다.
- 짝짓기: 불량 상자마다 그 상자의 `Arrive` 와 `ExpectChute` 대기열 순서상 그 상자에 대응하는 필터된 `Chute` 상승을 짝짓는다. 슈트 상승이 없는 상자는 통계에서 빼고 수를 보고한다.
- 교정 시드에서 F 정답 래더 연결 실행이 [PASS] 가 아니면 그 시드는 교정에 쓰지 않고 같은 묶음에서 `"TR-2026-05/calib/"` 다음 k 로 넘어간다. 넘어간 시드와 그 F 판정은 v1.0 에 모두 적는다.
- 음성 래더 재생성: `generate_3i.py` 의 같은 함수에 새 상수만 넣는다. `push-timing-off` 의 결함은 새 발사 지연을 기준으로 같은 +50 스캔(상대 오프셋)이고 `ignore-curtain` · `no-sort-check` 의 결함 줄은 원래와 같다. 원래 · M1 래더의 줄 단위 차이가 상수 칸에만 있음을 확인해 기록한다.
- 규칙이 낸 값을 사람이 고치지 않는다. 규칙대로 계산할 수 없는 경우는 위 표의 대체 규칙(바꾸지 않음)만 쓴다.
- 재교정은 래더 상수와 M1 참조 논리의 매개변수만 바꾼다. 플랜트 설계값(asm-pusher `cell_design`)과 물리값 목록은 M0 과 같다. 그래서 **M1 은 슈트 용량(센서 위치 · 대기열 길이)을 바꾸지 않는다**(§7 P3).
- 새 상수 · 새 래더 4개 · M1 참조 논리 매개변수표의 sha256 과 교정 실행 기록은 동결(§14) 뒤, 공식 실행 전에 만들어 v1.0 §10 에 적는다. 교정 결과를 본 뒤 §7 · §8 · §9 를 바꾸지 않는다.

### 6-2. 실행

- 실행기 `고정입력_TR-05/bridge/run.py`(plc-twin-lab `a362610` 다리를 줄이고 3i 셀 B 스위치를 넣은 사본, 출처 `SOURCES.json`)가 앱을 `vexplor_studio_native --external-control --cell <cell.plccell.json> --physics fast|mujoco` 로 띄우고, 표준 입출력의 JSON 한 줄 규약(`load {cell, seed, defect_rate}` → `set_constants` → 틱마다 `step {Q, stimuli}`)으로 돌린다. 앱 경로는 `--app` 또는 `TR05_APP` 으로만 받고 없으면 시작하지 않는다(기본 경로 없음). 래더는 `node bridge/engine.mjs <program.ldprog.json>`(동봉 plc-simulator `b415c25`, 10 ms 스캔). 셀 A 는 틱당 5 스캔, 셀 B 는 1 스캔. 직전 스캔의 Q 가 다음 틱의 Q(유지 Q). F 실행에는 언제나 앱 인자 `--report-first-contact` 를 붙인다(결정 (a), §3-1 보고 ②). 공식 회차는 회차 실행기 `bridge/round.py` 가 시드 표 · 고정값 파일 · 기대 실행 수를 읽어 돌린다(§10 실행 명령).
- 모드는 **CLI 로만** 준다. 실행기는 자식 환경에서 `VEXPLOR_EXTCTL_PHYSICS` 를 지우고, 적재 뒤 stderr 의 마지막 `EXTCTL_PHYSICS` 줄이 `mode=<기대값> source=cli` 인지, M 조건이면 적재 응답에 `state.physics` 가 있고 F 조건이면 없는지 확인해 `metadata.json` 에 기록한다(앱 sha256 · 커밋 · node 판 · 적재 시 `state.physics` 전체 포함).
- 감도용 셀 사본: 벨트 배율(`--belt-factor`) · 물리값(`--physics-value 이름=값`) · 초기 측면 위치(`--initial-z-offset`)가 있으면 실행 폴더에 셀 JSON 사본을 만든다(§6-4).
- 한 실행 = 앱 한 프로세스 + 엔진 한 프로세스. 병렬로 돌려도 결과가 같다고 가정하고, 이 가정은 결정성 반복(§6-3)으로 확인한다.
- 실행 범주는 `[VALID]` · `[PLANT_ERROR]` · `[INVALID]` 셋이다(§8). 판정은 `[VALID]` 실행에서만 센다.
- 셀 B 의 두 조건은 같은 틱(10 ms) · 같은 에지 분해능(1 ms)이다.

### 6-3. 결정성과 열린 고리 기준선

- **F 결정성 게이트**: 셀 A `normal` 의 3 래더, 셀 B 묶음 3 첫 배치의 (정답, `normal`) · (`push-timing-off`, `normal` 1,800) · (정답, `curtain` 1,000) · (`ignore-curtain`, `curtain` 500)과 묶음 5 첫 배치의 (정답, `recovery`) · (`no-sort-check`, `flow`) — 9쌍 — 을 2번씩 돌린다. 첫째가 그 쌍의 주 실행이다. **틱 기록 전체의 해시**(틱마다 I · 적용 Q · 다음 Q · 자극 · edges · 물리 사건 · 다리 판정 · state · 래더 스캔과 엔진 digest)가 같아야 한다. 다르면 실행 전체 무효(§8).
- **M 조건의 쌍별 반복**: M0 · M1 의 모든 (래더, 입력) 쌍(M0 56 · M1 50)을 2번 돌려 틱 기록 전체의 해시(M 은 `state.physics` 포함)를 비교한다. 두 번이 같으면 그 판정을 쓴다. 다르면 그 쌍만 10번 돌려 아래 10회 규칙으로 판정하고, 그 조건은 「비결정 쌍 있음」으로 적는다(P6 [틀림]).
- **10회 규칙**: 10번 가운데 같은 판정이 6번 이상이면 그 판정, 아니면 `[UNDECIDED]`. `[VALID]` 가 아닌 실행(`[PLANT_ERROR]` · `[INVALID]`)은 「판정 없음」으로 세며 분모에서 빼지 않는다(그래서 그런 실행이 5번 이상이면 `[UNDECIDED]`). **뒤바뀜** = F 의 판정과 다른 판정이 다수 판정인 경우. `[UNDECIDED]` 는 §7 결측 규칙으로 센다.
- 개발 실행에서 M0 은 셀 A `normal` · `cycle-stop`, 셀 B `normal` · `curtain`(시드 1)에서 2/2 같았다(§4-2).
- **열린 고리 재생(기준선)**: F 조건의 셀 B 정답 래더 `normal` 12 실행과 셀 A 정답 래더 2 실행에서 매 틱 보낸 `step` 요청(Q · 자극)과 `set_constants` 를 기록(`trace.jsonl`)해, 래더 없이 같은 순서로 M0 플랜트에 그대로 보낸다. 잰다:
  - 센서 입력 태그별 상승 · 하강 에지 시각 차이(M − F, ms, F 에지 순서대로 짝지음): F 에지 수 · 짝 수 · 짝 없는 에지 수 · 평균 · 중앙값 · 최대 절댓값.
  - 부품별 최종 경로 일치 수(셀 B), PART_DROP 유무와 틱(셀 A).
  - 뒤바뀐 배치마다 열린 고리 슈트 나이(§6-1 짝짓기)가 원래 창 165~235 밖인 상자 수, 슈트 센서 하강이 없는 구간 수.

### 6-4. 감도 실행

M0 를 기준으로 한 번에 한 항목만 바꾼다. 감도 설정은 두 표로 나눈다 — **P8 설정**(예측 P8 의 집계 대상)과 **모형 가정 설정**(보고만, 예측 없음).

**P8 설정(8개)** — 대상: 정답 래더 셀 B `normal` 12 배치, 셀 A 정답 · 음성 래더 `normal` · `cycle-stop`(셀 A 는 마찰 · 벨트만).

| 항목 | 값 | 적용 | 방법 |
| --- | --- | --- | --- |
| 원호 마찰 | × 0.5 · × 1.5 | M 장면의 원호 면만(슈트 x 힘이 빼는 원호 등방분에도 같은 배율 — 원호 위 x 총 감속은 그대로, 경사 방향 마찰과 yaw 가 바뀜) | 셀 JSON `physics.values.transition_mu_scale`(M 전용, 기본 1) |
| 벽 마찰 `wall_friction` | 0(기준) · 0.3 | M | 셀 JSON `physics.values.wall_friction` |
| 슈트 x 힘(`chute_x_mu` 이식) | 켬(기준) · 끔 | M | 셀 JSON `physics.values.chute_x_force` = 0(M 전용, 기본 1) |
| 마찰 계수 | × 0.7 · × 1.3 | M | 셀 JSON `physics.values.friction_scale`. ×1.3 은 상자 μs 0.8 → 1.04, chute_x_mu 0.85 → 1.1 로 컨베이어 상자로는 높은 값이다 |
| 벨트 속도 | × 0.95 · × 1.05 | **F 와 M 둘 다** | conv-belt 인스턴스 `parameters.speed_mps`(셀 B 는 다섯 인스턴스 모두). `design.belt_speed_mps` 는 그대로. 3i 래더의 BELT_SPEED_DEVIATION 띠(허용 0.05 + 추정 오차 0.015) 안. `values_sha256` 만 바꾸고 `setup_sha256` 은 바꾸지 않는다 |

**모형 가정 설정(10개, 보고만)** — 대상: 셀 B 정답 래더 `normal` 에서 M0 이 뒤바뀐 배치 전부(f 개)와, 뒤바뀌지 않은 배치 2개(묶음 3 · 4 각각에서 뒤바뀌지 않은 첫 배치). 실행 수 10 × (f + 2).

| 항목 | 값 | 적용 | 방법 | 보는 것 |
| --- | --- | --- | --- | --- |
| 센서 윤곽 | 고정 치수(기준) · 회전 외접 상자 | M | `physics.values.sensor_footprint_rotated=1`(M 전용, 기본 0). 앱 시험: 실제 셀 B 광학 프레임에서 외접 상자 계산 검산, 시드 1 열린 고리 450 틱에서 chuteSensor 덮임 증가 · 벨트 센서 불변 | P1 원인 사슬의 센서 가정 |
| 스텝 | 0.001(기준) · 0.0005 s | M | `physics.values.fixed_step_s=0.0005`(틱당 셀 B 20 스텝). solref 시간 상수 0.01 s 는 스텝과 독립이라 접촉 강성은 바뀌지 않는다 | 수치 수렴 |
| 원호 면 수 | 10(기준) · 20 | M | `physics.values.transition_facets=20` | 이산화 |
| 데크 마찰 혼합 | 정지 가중 1(기준) · 0 | M | `physics.values.deck_friction_static_weight=0` | 미는 동안의 미끄럼(운동 마찰) |
| 비틀림 마찰 | 0.005 m(기준) · 0 · 0.02 m | M | `physics.values.torsional_friction_m` | yaw 저항 |
| 초기 측면 위치 | 0(기준) · +0.005 · −0.005 m(모든 부품) | **F 와 M 둘 다, 셀 B 만**(셀 A 는 측면 위치 모형이 없어 앱이 거부 — 결정 (c)) | 셀 사본의 부품 인스턴스 `transform.position[2]`(\|z\| ≤ 0.125 확인, 적재된 z 가 요청과 다르면 그 실행 거부) | 작은 섭동에서도 뒤바뀜이 유지되는가 |

- 결과는 「그 뒤바뀜이 몇 개의 설정에서 유지되는가」로 적는다. 스텝 0.0005 에서 뒤바뀜이 사라진 배치는 「수치 기인 가능」으로 표 1 에 표시한다. 감도 실행으로 예측을 판정하지 않는다(P8 제외).
- 물리값 설정은 셀 B · 셀 A 모두 `setup_sha256` · `values_sha256` 을 바꾼다. 벨트 배율 · 초기 측면 위치 설정은 **셀 B 에서** `values_sha256` 만 바꾸고 `setup_sha256` 은 그대로다. 셀 A 의 벨트 배율은 두 해시 모두 그대로다(셀 A 해시는 플랜트 매개변수를 넣지 않는다, §3-1). 설정별 해시는 §10 · 시드 표에 고정한다.
- 스텝 0.0005 설정에서도 첫 접촉 표본은 「그 ms 시작 자세」로 정확하다(§3-1 보고 ② 의 표본 규칙).

### 6-5. 측정 (실행마다)

| 측정 | 정의 |
| --- | --- |
| 실행 범주 | `[VALID]` · `[PLANT_ERROR]` · `[INVALID]`(§8) |
| 판정 | 시나리오별 판정(§3-5) · 셀 B 공정 판정은 장부 무관 판정도 |
| 사건 코드 묶음 | 물리 사건 (이름, 규칙 코드) 다중 집합 + 다리 판정 + 첫 잠금의 틱 · FaultCode + 끝 FaultCode |
| 처음 갈라진 사건 | 같은 (래더, 입력)의 F 실행과 **무엇이 일어났는가**로 비교한다 — 첫 잠금 FaultCode, 물리 사건(이름 · 규칙 · 부품)과 다리 판정의 순서, 부품 최종 경로. 같은 사건의 시각 차이만은 갈라짐이 아니다. 다른 것 가운데 가장 이른 틱을 고르고, 같은 틱이면 잠금 > 사건 > 판정 > 경로. FaultCode 13 의 슈트 창 · out 창은 원래 래더 엔진 재생으로 잠금 스캔의 필터 상승 · 대기열 나이를 보고 가린다 |
| 완료 항목 | 셀 A 방문 · Rounds · 끝 Q / 셀 B 부품별 경로 · Arrivals |
| M 진단 | `state.physics`: `values_sha256` · `setup_sha256` · `rules[]` · `max_tilt_rad` · `max_yaw_rad` · `tilt_flag` · `plate_track_max_m` · `parts[]` · `first_contact[]` |
| 참조 일치(정답 래더) | 첫 잠금 전 차이 건수 · 예외로 뺀 차이(틱 · 태그) · 첫 잠금 뒤 차이 건수(태그별) |

## 7. 가설 · 사전 예측 · 판정선 (동결 전에 숫자로 고정) [동결]

**이 절은 §14 의 동결 대상이다. 교정 실행 · M1 재생성 · 개발 시드 끝까지 실행 · 공식 실행은 이 절을 동결한 뒤에만 한다.** v0.4 교차 검토에서 판정선을 한 번 조정했다(D18 — 조정 내역은 `_agent/TR-05_교차종합_2026-10-08.md` §3). 그 뒤로는 바꾸지 않는다.

**주 가설** — 셀 B(3i)에서는 플랜트 모형 선택(§1 의 묶음 M) 하나가 정답 래더의 판정을 바꾸고(F [PASS] → M [FAIL]), 그 뒤바뀜은 래더 상수를 MuJoCo 로 다시 구해도 남는다. 음성 래더의 결함 검출은 두 모형이 거의 같다. (셀 A 정답 래더는 예측하지 않는다 — §5-1.)

**판정 규칙.** 비율은 정수식(예: 「x/n ≥ 3/4」 = 4x ≥ 3n)으로 한다.

**원인 분류.** 뒤바뀐 쌍(F 와 다른 판정)은 처음 갈라진 사건으로 넷으로 나눈다 — (가) 래더 잠금(FaultCode) (나) 물리 사건 · 다리 판정 (다) **완료 항목만**: 첫 잠금 FaultCode 가 0 이거나 F 와 같음, 물리 사건 · 다리 판정 없음, `Arrivals == 20`, 그런데 부품 경로가 완료 조건을 만족하지 않음(장부 기인) (라) 그 밖. (다)는 부품별로 원인(출력 줄 휨 · `on_floor` · `stacked` · 기타, `parts[]` 표시)을 적는다. **P1 · P2 · P3 · P8 · F1 · F3 의 뒤바뀜은 (가)+(나)+(라)로 세고, (다)는 같은 표에 따로 적는다.** 장부 무관 판정(§3-5)도 함께 적는다.

**결측 규칙(모든 P · F 에 적용).** 예측 대상 쌍 가운데 판정이 정해지지 않은 쌍(`[VALID]` 아님 또는 `[UNDECIDED]`)이 있으면, 그 쌍들을 예측에 가장 유리하게 채운 결과와 가장 불리하게 채운 결과를 각각 계산한다. 둘이 같으면 그 결과로 적고, 다르면 `[판정 불가]` 로 적는다(맞음 · 틀림 어느 쪽에도 세지 않는다). 판정이 정해진 쌍만으로 센 값도 분자/분모로 함께 적는다. 대상이 0 이 되는 예측은 `[판정 불가]` 다.

**검출 지표 두 가지**
- **주 지표 — 기대 사유 검출** = 음성 래더 실행의 판정 [FAIL] ∧ §3-4 의 기대 사유가 사건 코드 묶음에 있음. 대상 **28쌍**: 셀 A 4(음성 2종 × `normal` · `cycle-stop`) + 셀 B 24(`push-timing-off` 12 · `ignore-curtain` 12). `no-sort-check` 는 3i 에서 기대 사유를 내는 곳이 없어 뺀다(§3-4, L2).
- **보조 지표 — 판정 검출** = 음성 래더 실행의 판정 [FAIL]. 대상 **29쌍** = 28 + `no-sort-check` 1. 이 가운데 `push-timing-off` 12 · `no-sort-check` 1 = 13쌍은 실행 길이가 생산 완료보다 짧아 어느 모형에서도 [FAIL] 이 정해져 있다. 보조 지표는 이 13쌍과 나머지 16쌍(셀 A 4 · `ignore-curtain` 12)을 나눠 적고, 모형 간 차이의 해석은 16쌍에 한정한다.

**재현 예측(예비 관찰을 보고 세움)**

| 번호 | 예측 | 판정선 | 예비 근거 |
| --- | --- | --- | --- |
| P1 | 셀 B 묶음 5(불량 5개) 4 배치의 정답 래더 `normal` 에서 「F [PASS] ∧ M0 [FAIL] ∧ M0 의 첫 잠금 FaultCode = 3(슈트 가득) ∧ 원인 분류 (가)」인 배치가 3개 이상 | 2개 이하면 [틀림] | 시드 1(불량 5): 내장 제어기 · 3i 래더 둘 다 M0 틱 1710 첫 잠금 FaultCode 3, F [PASS]. 근거는 같은 배치 하나다 — 방향은 받치고 비율은 기전 논리(수거 없음 → 묶음 5 는 모두 슈트에 5개, F 여유 간격당 0.036 m)로만 받친다 |
| P7 | 열린 고리 재생(셀 B 12 배치)에서 atStopper · out · isBad 세 태그의 F 상승 에지 전부를 합친 n 개 가운데 M 에 짝이 있고 \|M − F\| ≤ 10 ms 인 것이 x 개일 때 **10x ≥ 9n**(짝 없는 F 에지는 벗어난 것으로 셈). 그리고 슈트 센서의 짝지은 상승 에지(12 배치 합) M − F 의 중앙값(짝수 개면 가운데 두 값의 평균) > 0 | 둘 중 하나라도 벗어나면 [틀림] | 시드 1: 짝 약 40개 모두 ≤ 10 ms(최대가 정확히 10), 슈트 평균 +164 ms(짝 5개). 0/40 이 받치는 비율 하한은 약 92.8 % 라 90 % 로 둔다 |

**새 예측 · 확인**

| 번호 | 예측 | 판정선 |
| --- | --- | --- |
| P2 | 셀 B 묶음 3 · 4(불량 3 · 4개) 8 배치의 정답 래더 `normal` 에서 뒤바뀜(F ≠ M0, 분류 (가)+(나)+(라))이 2개 이하 | 3개 이상이면 [틀림]. 위험이 있는 예측이다 — 시드 1 열린 고리의 슈트 차이 최대 390 ms 가 창 반폭 350 ms 를 넘어 FaultCode 13 으로 뒤바뀔 수 있다 |
| P3 | P1 의 조건을 만족한 M0 배치 n0 개 가운데, M1 에서도 「F [PASS] ∧ M1 [FAIL]」(분류 (가)+(나)+(라))인 배치 x 개가 **2x > n0**. **구조 확인 예측이다**: M1 은 슈트 용량을 바꾸지 않으므로(§6-1) 대기열 기하로 생긴 FaultCode 3 뒤바뀜은 남을 것으로 본다 | n0 = 0 이면 `[판정 불가]`. 2x ≤ n0 이면 [틀림]. 반대 방향(F [FAIL] · M1 [PASS])은 세지 않고 따로 적는다. FaultCode 3 뒤바뀜과 그 밖을 나눠 적는다 |
| P4 | 주 지표 28쌍 가운데 F 와 M0 의 기대 사유 검출 여부가 다른 쌍(불일치 쌍)이 **1개 이하** | 2개 이상이면 [틀림]. 검출 수 차이도 표 2 에 적는다 |
| P5 | 셀 A 음성 2종 × 2 시나리오 4쌍이 F · M0 모두에서 PART_DROP 으로 검출된다(셀 A 음성의 M0 은 보지 않았다) | 하나라도 검출되지 않으면 [틀림] |
| P6 | F 게이트 9쌍이 같고, M0 · M1 의 모든 쌍에서 두 번 실행이 같다(비결정 쌍 0) | 한 쌍이라도 다르면 [틀림](실행은 §6-3 으로 계속) |
| P8 | P1 의 조건을 만족한 배치 n 개 각각에서, 실제로 돌린 P8 설정 k 개(계획 8) 가운데 「그 설정의 F [PASS] ∧ 그 설정의 M [FAIL](분류 (가)+(나)+(라))」인 설정 수 h 를 센다(M 전용 설정의 F 는 기준 F 결과를 쓴다. 그 설정의 F 가 [FAIL] 이면 유지가 아니다). **8h ≥ 5k** 인 배치를 「유지 배치」라 한다. 예측: 2 × 유지 배치 > n | n = 0 이면 `[판정 불가]`. 2 × 유지 배치 ≤ n 이면 [틀림]. k 가 8 보다 작으면 그 k 로 판정하고 빠진 설정을 적는다. 실제로 돌린 설정이 0 개인 배치가 있으면 P8 은 `[판정 불가]` |

**반증 조건**

| 번호 | 조건 | 틀린 것으로 적는 주장 |
| --- | --- | --- |
| F1 | 셀 B 정답 래더 25쌍(`normal` 12 · `curtain` 12 · `recovery` 1)에서 F ≠ M0(분류 (가)+(나)+(라), 두 방향)인 쌍이 0 | 「모형 선택이 이 셀의 정답 래더 판정을 바꾼다」 |
| F2 | 주 지표 28쌍의 불일치 쌍 ≥ 2 | 「두 모형의 결함 검출은 거의 같다」 |
| F3 | 셀 B 정답 래더 25쌍에서 「F [PASS] · M1 [FAIL]」(분류 (가)+(나)+(라))인 쌍이 0 | 「재교정해도 뒤바뀜이 남는다」. 이때 M1 셀 B 음성의 주 지표 검출 수가 M0 이상이면 「뒤바뀜이 상수 출처로 설명된다」로, M0 보다 적으면 「재교정이 결함 검출을 낮추면서 뒤바뀜을 없앴다」로 적는다. 반대 방향은 따로 적는다 |

- 합격/불합격 없음. **결과는 어느 쪽이든 공개한다**(대표 확인 행). 틀린 예측은 고치지 않는다.
- 뒤바뀜은 방향(F [PASS] → M [FAIL], 또는 반대)을 나눠 센다. 반대 방향은 예측하지 않았고 나오면 따로 적는다.
- 판정 검출(보조 지표)의 F · M0 차이는 예측 없이 적는다.

## 8. 실행 무효 기준 · 재시도 · 탐색적 보고 [동결]

**실행 시작 전 거부**: 실행기 · 회차 실행기 · 표 · 독립 검산 · 공개본 변환 · 시드 표 생성기 · 교정 측정기 스크립트 · 래더(원래 7개 · M1 재생성 4개) · M1 참조 논리 매개변수표 · 셀 파일 · 시드 표 · 고정값 파일 가운데 하나라도 sha256 이 §10 과 다르거나, 앱 실행 파일 sha256 · libmujoco sha256 이 다르거나, 빌드 커밋이 40자 16진수가 아니면 실행기가 시작하지 않는다.

**공식 회차 전 양성 대조**
1. **빠른 모형 회귀 게이트**: 공식 빌드에서 ① extctl 회귀 시험(`external_control_(plant|protocol|controller|corridor|pack|physics|sort_physics|e2_values|e2_report)` · `vexplor_physics_world_tests` · `vexplor_process_cell_tests`, 11개) 모두 통과(plant · protocol 은 셀 B 빠른 모형을 고정 참조와 4,000 틱 틱마다 비교) ② `tr05.py gate` 로 F 조건 3i 검증 묶음(셀 A 시드 1, 셀 B 시드 1 · 2 · 3: 부품별 분류가 `plc-devices-3i-4a-seed-results.json` 과 같음, 정답 래더 참조 차이가 §8 ② 예외 외 0건이고 예외는 시드마다 틱 4461 에서 정확히 1건, 음성 4종 검출 · `no-sort-check` [FAIL])가 macOS `3i-final-2` 와 항목마다 같음. 이미 본 입력이라 공식 결과에 넣지 않는다.
2. **개발 시드 끝까지 실행**(동결 뒤): 개발 시드 묶음마다 1개로 셀 B 정답 `normal` 을 F · M0 · M1 각 1회, 회차 실행기 · 표 · 독립 검산 · 공개본 변환까지 통과. 그 판정은 v1.0 §4 에 「동결 뒤에 본 개발 관찰」로 모두 적고, 예측을 바꾸는 근거로 쓰지 않는다.
통과하지 않으면 공식 실행을 하지 않는다.

**실행 범주**
- `[VALID]`: 앱 · 엔진 종료 정상, 모든 틱의 응답 `ok:true`, 기대한 모드 확인(§6-2), `summary.json` 의 `ticks` 가 §3-5 표의 값, M 조건이면 `setup_sha256` 이 §10 의 셀별 값(감도 설정이면 그 설정의 값)과 같고 `values_sha256` 이 시드 표의 값과 같음, 결과 파일(`summary.json` · `metadata.json`)이 있음.
- `[PLANT_ERROR]`: M 에서 MuJoCo 경고로 틱이 거부된 실행(앱 메시지 `MuJoCo warning … tick rejected`). 판정이 아니며 [FAIL] 로 세지 않는다. 그 쌍의 두 번 실행(§6-3)이 모두 `[PLANT_ERROR]` 이면 다시 하지 않는다. 한 번만이면 그 쌍은 비결정 쌍으로 보고 10회 규칙을 쓴다.
- `[INVALID]`: 그 밖의 비정상 종료 · 시간 한도 · 모드 확인 실패 · 틱 수 불일치 · 정리 실패.

**실행 전체 무효**(모든 판정을 「무효」로 적는다):
1. F 결정성 게이트 실패.
2. **정답 래더 실행 어디서든, 틱 0 부터 그 실행의 첫 잠금 전까지, 그 조건의 참조 논리(F · M0 = 원래, M1 = M1 참조 논리, §3-5)와의 차이가 1건 이상** — 단 다음 모양의 차이 하나는 조건(F · M0 · M1)과 무관하게 세지 않는다(문서화된 예외, fe605e1 `verify_3i` 53행이 허용한 「생산 완료 뒤 1 스캔 빠른 정지」 — 무공급 정지 계수의 시작점이 래더와 참조에서 한 스캔 다름): 첫 잠금 전 구간(틱 < 첫 잠금 틱 — 잠금 스캔 자체는 뒤)에서 차이가 나는 스캔이 정확히 1개(스캔 s — 앞뒤 스캔과 붙지 않은 한 스캔)이고 ∧ s 에서 다른 태그 집합이 정확히 {B.Conv.run, B.Lamp.green, B.Lamp.yellow} 이고 ∧ 래더의 B.Conv.run = 0 · 참조 = 1 이고 ∧ s + 1 에서 세 태그가 다시 같고 ∧ s 가 `probes.Arrivals` 가 20 이 된 틱 뒤이며 그 실행의 마지막 `Arrive` 스캔 + 무공급 정지 상수(3000) ± 1 스캔 안에 있다. 이 모양의 항목이 한 실행에 둘 이상이면 둘째부터 센다. 실행기는 이 판정을 기계로 하고 예외로 뺀 차이의 틱 · 태그를 실행마다 기록한다(개발 시드 1 · 2 · 3 의 F 에서는 틱 4461). **첫 잠금 뒤의 차이는 무효에 쓰지 않고 태그별로 보고만 한다.** 이 규칙은 개발 실행에서 M0 셀 B 시드 1 의 잠금(틱 1710) 뒤 램프 차이 3,291 스캔을 본 뒤에 정했다(L1). v0.3 문안(「어디서든 > 0」)대로면 문서화된 1 스캔 때문에 모든 회차가 무효가 된다.
3. 한 M 조건의 주 실행 + 2회째 반복(M0 112 · M1 100, 10회 규칙이 걸린 쌍은 그 실행 수 포함)에서 `[PLANT_ERROR]` 가 10 % 초과 — 정수식 10 × 오류 수 > 실행 수(M0 12건 이상 · M1 11건 이상). 감도 · 교정 · 열린 고리 실행은 세지 않고 조건 · 묶음별로 따로 적는다.
4. 기대 실행 수만큼의 행이 없음 — 주 162, M 2회째 106, F 게이트 2회째 9, 열린 고리 14, P8 감도 156, 모형 가정 설정 10 × (f + 2), E4 100. 10회 규칙이 걸린 쌍은 그 쌍의 실행이 10 이 된다. 교정 실행 수는 v1.0 에 적는다.
5. 모드 확인 실패가 한 건이라도 있음(조건이 섞임).

**재시도**: `[INVALID]` 실행은 같은 입력으로 최대 2번 다시 하고 모든 시도를 남긴다. 실행 전체가 무효면 새 폴더에서 처음부터, 같은 원인으로 최대 2번, 모든 시도를 공개한다. 무효 · 중단 폴더는 지우지 않고 `_invalid/<시각>_<원인>/` 로 옮긴다.

**탐색적 보고(가설 없음 — 주 결과와 분리)**
- E1 뒤바뀐 쌍마다 처음 갈라진 사건 · 그 틱 · M 의 `rules[]`, 처음 갈라진 사건 직전 50 틱의 슈트 · 출력 대기열 부품별 yaw · `support_gap_m` · `stacked` · `on_floor`, 그리고 **사전 대응**: 아래 표로 처음 갈라진 사건을 §3-2 의 행 하나에 대응시키고 그 행의 「같은가」 값을 그 뒤바뀜의 분류로 적는다.

| 처음 갈라진 사건 | §3-2 행 | 분류 |
| --- | --- | --- |
| 첫 잠금 FaultCode 3 · 슈트 센서가 띠 안 정지 상자로 켜진 채 | r5(대기열 상한 · 간격 · 끝 브레이크) | 다름 |
| 첫 잠금 FaultCode 13(슈트 창) | r3(미는 동작) | 접촉 계산으로 바꿈 |
| 첫 잠금 FaultCode 13(out 창) · 4 · 출력 쪽 route 0 | r8(출력 도착) | 허용 오차를 더함 |
| 첫 잠금 FaultCode 5 | r1(벨트 위 이송) | 접촉 계산으로 바꿈 |
| CENTER-SNAP | r10 | 근사 |
| FLY-SIDE · PUSH-RETURN · FLY-01 · FLY-02 · PUSH_MISSED | r11 | 사건 같음, 결과 다름 |
| FLOW-QUEUE | r12 | 사건 조건 같음 |
| CHUTE-01 · CHUTE-HOLD | r6 | 같은 효과를 내도록 옮김 |
| PART_DROP(셀 A) | r15 | 같음(+보조) |
| `on_floor` 부품의 route 0 | r16 | 다름 |
| `stacked` 부품이 놓친 센서 에지 | r17 | 다름 |
| 그 밖 | — | 분류 불가 |

- E2 정답 래더 사건 코드 묶음의 F · M0 · M1 차이(판정이 같아도), 첫 잠금 뒤 참조 차이(태그별).
- E3 M 의 회전 보고(부품별 슈트 포착 틱의 yaw 와 정지 뒤 yaw, 데크 위 상자의 `run_max_yaw_rad` · `tilt_flag` 첫 틱), `stacked` · `on_floor` 가 켜진 부품 수, 출력 줄 휨(route 0 으로 남은 양품 수).
- E4 TR-2026-03 셀 A 연동 제거 변종 25종의 F · M0 판정 — 「드러남」 수의 차이(D9).
- E5 실행 비용(틱당 ms, 조건별).
- E6 셀 A 정답 래더의 F · M0 판정(`normal` · `cycle-stop`) — 등록 전에 M0 결과를 봤으므로 확인 예측 없이 적는다(L3).
- E7 판정 검출(보조 지표 29쌍: 13쌍 · 16쌍)의 F · M0 · M1 값.
- E8 모형 가정 설정(§6-4)별 뒤바뀜 유지 수.

## 9. 분석 계획 [동결]

- 표 1: 셀 · 조건별 정답 래더 판정(쌍마다), 뒤바뀜 수(방향별 · 원인 분류 (가)~(라)별), 장부 무관 판정, 묶음별(셀 B), 조건 · 묶음별 `[PLANT_ERROR]` 수, 「수치 기인 가능」 표시. 셀 A 정답 래더 행은 「탐색(E6)」, 셀 A 의 M1 열은 「M1 = M0(실행 없음)」.
- 표 2: 음성 래더 쌍별 기대 사유 검출 · 판정 검출, 조건별 합, 불일치 쌍 수(주 지표 28쌍 · 보조 지표 13쌍 · 16쌍을 나눠).
- 표 3: 열린 고리 센서 에지 차이(태그별 F 에지 · 짝 · 짝 없음 · 평균 · 중앙값 · 최대 절댓값), 최종 경로 일치, 뒤바뀐 배치의 원래 창 밖 상자 수.
- 표 4: P8 감도 — 뒤바뀐 배치별 유지 설정 수, 설정별 뒤바뀜 수.
- 표 5: 모형 가정 설정 — 배치별 · 설정별 판정.
- 표 6: 두 모형 기능 차이(§3-2)와 각 뒤바뀜의 사전 대응(E1).
- 표 7: 참조 일치 — 실행별 첫 잠금 전 차이 · 예외로 뺀 차이 · 첫 잠금 뒤 차이.
- 표 8: M1 재교정 — 상수별 F · M 통계, 새 값, 「재교정 불가」 · 「바꾸지 않음」 사유, 건너뛴 교정 시드.
- 신뢰 구간 · 검정 통계는 내지 않는다(배치는 시드 규칙으로 뽑은 12개이며 무작위 표본의 불확실성과 같지 않다). 분포와 쌍별 값을 모두 적는다.
- 독립 검산: 실행기의 집계를 읽지 않고 원 결과 파일(또는 공개본의 실행별 축약 파일)에서 범주 · 판정 · 장부 무관 판정 · 원인 분류 · 검출 · 뒤바뀜 · 참조 일치 무효 판정(예외 모양 포함) · 결측 규칙 · 예측 판정까지 다시 계산해 표와 전부 대조한다.

## 10. 고정 항목 (sha256 — v1.0 최종)

모든 값은 고정값 파일 `고정입력_TR-05/fixed.json`(sha256 `532167ac1078b01ea5b4b9a42dd3ca2879a3d23e707dccab9c89b8024eae4442`)에 들어 있고, 회차 실행기는 시작 전에 이 파일의 해시와 그 안의 해시를 모두 확인한다(같은 명령으로 두 번 만들어 바이트가 같음을 확인). `SOURCES.json` `88d0920e2880977e7bf93c4f21c8debe4e1affa975e6a33c854613599447d98d`(62 파일, `fixed.json` 줄의 초안 해시는 「동결 뒤 변경」 5행).

| 항목 | 위치 · 값 |
| --- | --- |
| 빌드 커밋 | vexplor-vision-2 `feature/tr05-e2` `ac78d02fbc84b35f041f4fcca2047a0c80c67930`(작업 트리 깨끗) |
| 실행 파일 | `native/build-linux/vexplor_studio_native` `d58c3928beb94958f6128d1579bdb1dc521f14b7edda8e4ca04bff7d29d6a25a`. 우분투 PC(linux-arm64, Ubuntu 24.04.5, NVIDIA GB10), conda clang 21.1.8(aarch64-conda-linux-gnu), Release, `-ffp-contract=off`. 화면 없음(`--external-control`). ctest 11/11 |
| MuJoCo | 3.12.0, `libmujoco.so.3.12.0` `ddc46a81d9acfdd3afec7ac4723350a1a5e21ac5ce774ab7e904921f20c3a36d` |
| Node | v24.21.0. 래더 엔진 vendor 트리(plc-simulator `b415c2510b47e022645489e3c29c34429ed84705` dist와 런타임 의존 모듈) `7b384a14…`(64자 전체는 `SOURCES.json` 의 `plc_simulator.tree_sha256`) |
| 엔진 설정 | 고정 스텝 0.001 s(셀 A 틱당 50 스텝, 셀 B 10 스텝), implicitfast, elliptic, 솔버 반복 80, condim 6, solref 0.01 · solimp (0.95, 0.99, 0.001)(코드 고정), autoreset 끔, 경고 시 예외, 에지 분해능 1 ms |
| 해시 셀 A | 규칙 v1, 15개 목록(§10-1). 기본 values `5703c07092178d7068d71338df3e1e663f957f4576571ba9d4cb09ce273ec883` · setup `1405abba91c61d3d86ec41943aa45acc3fcbc955f62034e80224027beef31111`. 감도 setup: `friction_scale` 0.7 `5b3c5ccc0dbc1854d5b597e0f1324bda9914a3d33f31d2a911df314144423519` · 1.3 `5948faf7f9862f04913af10965b7f44ae3a6560498c979971e576a7e65ec8984`, 벨트 배율 = 기본 setup |
| 해시 셀 B | 규칙 v4, 32개 목록(§10-1). 기본 setup `f2f70763e25b2cdc5480c3f4491aa18b2cb97ea190b9d6b5f5b055f8eef2111d`(모든 시드 같음). 감도 setup: `transition_mu_scale` 0.5 `88618aa9838a755cb6dce6645ea2e4ba35db3e08bc7658b0c428022d4013868b` · 1.5 `24b1aaa2647f7c2c5ce7bb0446b4538aa7beff8c6e91787a7c15dcd80e37817e`, `wall_friction` 0.3 `d065af0d41118fc8240e85007eb825d7ea540c83462063c279c66ec7c99506f6`, `chute_x_force` 0 `15b9874de41360c2a11640e6eef2aaf3530bf7c35348ee1505abd46a08299661`, `friction_scale` 0.7 `4c67c6326742b38d47f465a02726fdba4c0217a4b6d0c3ab8d115dc07f319d5e` · 1.3 `10523069853729114d9991bc0479930ba3343b2a30c48d604d3066974d8357c4`, `sensor_footprint_rotated` 1 `b7e7901ecaa8f6f0e4f0a65f3c389e7cfd8589debc0259d4ecf35f9dad928c8f`, `fixed_step_s` 0.0005 `4cd9a06a71e4c596813cc6491701ad39b721d2479380e39da924af8055ee0418`, `transition_facets` 20 `48d8acb83e83edcff66ae5c7bfc16abc15d1a21bd7617681bb904c53d5640771`, `deck_friction_static_weight` 0 `5e1d498c503acf80a7b7cc7612dd1342dd5c2e1a34f4c0bf6ca947465758cb37`, `torsional_friction_m` 0 `d12422ef640952dcbabfa8ea1bde8297af65c727353d426f124c979be77a63d5` · 0.02 `51a6cd78598ad5d7f431bd21271a7b3ea1c5421609c34b716f864f3767fd5da1`. 벨트 배율 · 초기 측면 위치 = 기본 setup. 시드 표의 설정별 setup 17개가 이 값과 모두 같다 |
| 시드 표 | `고정입력_TR-05/seed-table.json` `d02d62f3975411e3d01b3a58d0c50eb740ffe2b46375c04928788b4bdee3c320`(동결 커밋 `3a12187…` 을 넣어 생성, 조사한 k 52 — k ≤ 35, 모든 k 기록) |
| 공식 시드(묶음: k → 시드) | 3: 1→682508701 · 3→2701952951 · 5→1584772094 · 7→1409986221 / 4: 4→3162308072 · 6→3637394171 · 15→2033289244 · 18→3814400361 / 5: 12→352593554 · 17→1829005345 · 32→692445127 · 35→3570567229 |
| 교정 시드 | 3: 1→1865575037 · 7→4002380191 / 4: 3→2948004803 · 5→3127217929 / 5: 2→1050778556 · 9→983796061 |
| 개발 시드 | 3: 8→18032821 / 4: 4→2981378262 / 5: 7→2617252722. 세 집합은 겹치지 않고 시드 0~3 도 없다 |
| 셀 B 시드별 기본 values(앞 16자, 64자 전체는 시드 표) | 공식: 682508701 `11016a25531efe48` · 2701952951 `ad849943b158c2f9` · 1584772094 `9f1da266ddb90bdc` · 1409986221 `63705eb68596dbaa` · 3162308072 `cc973273e9d4df00` · 3637394171 `ed2165976f64aefc` · 2033289244 `9621355b205ecb92` · 3814400361 `84aa504a2c99d1bb` · 352593554 `8c6a2a686eeda357` · 1829005345 `54d66a18df6df429` · 692445127 `2fcaa70ee8cd6985` · 3570567229 `3e77fe2fc670e667`. 교정: 1865575037 `05a9286b5323b324` · 4002380191 `26eaf1a001f96c26` · 2948004803 `aa763d5afa121e09` · 3127217929 `483f6a5de810b85e` · 1050778556 `db6d5860b4423459` · 983796061 `8fe5ba8766d116cf`. 개발: 18032821 `72c9e278ab9f3c66` · 2981378262 `d563a4a1041d6b2b` · 2617252722 `0c3b8c3869e3d2b8` |
| 셀 · io-map · 설계 파일 | 셀 A `cell-a-shuttle.plccell.json` `8fbf8ea6afed7ab95fda1d0db457796da0ed131a826a246d678a4bdb972bc9d2` · io-map `8e4d059a536fb86ff4955f1887ef4bb0ebf9a1cdac4642141472479605fdfd4e`. 셀 B `cell-b-sort.plccell.json` `38e9b8c3d556feaa904dfc89c9f25eaf9d17d6fdafa711aabcfaa0b94fdbe9c7` · io-map `10dd4faab284eddb0e0a5cd949f0788c438174ca2fd58e145850a98503163fc4`. asm-pusher 1.5.0 `device.json` `647781cf8eeeebdb49684a130074fb9961ed98f0baa78cb1d3f984540a0006f9`. 분류 기준 `plc-devices-3i-4a-seed-results.json` `fe840e193587c31c78f8853ab36eb152df56e6c4d3eac848c7b3161391b47d25`. `phase3c-control.json` `bd85b51f0633969afdaaf54fc76c9e1a36883fc2ccd995531236091df41a7f25`. 태그 맵 · `cells/*.json` 사본 45 파일은 고정값 파일에 |
| 참조 논리 | extctl `native/tests/external_control/logic.py` `67811ac4609918f466e604e1462b9b8019a19febcbede5ad7e2ac23c6cf52de0`(앱 쪽, 고치지 않음). 개정 1 의 반 스캔 안쪽 여유는 `refcheck.py`(아래) 안에 있다 — 적용 값 슈트 2.0/0.3525 · 출력 2.335/0.3575 · 가득 0.445 |
| 래더(원래) | 셀 A 정답 `5058bd0b97644e66c0310a540a0403931bf6bd8195445576430d6dd1cabf8ef1` · late-reverse `76018c387dddc09aa5411da241897c1ba20a4629844c301ccd3200140f1b7aa1` · swapped-sensors `7fd10917b31949e24528fbc5398501cdd9852cda18537af07671c0d308e8c6e5`, 셀 B(3i) 정답 `eb44ce59b386e175ab22255f684dbd277b27e00906fb0b92d81703e7f389209f` · push-timing-off `78951c5517af831727f5518d5d31b0ad9a702ff0feb605b45a590afe829f4010` · ignore-curtain `396aa80ffa273e6d0374ffd8a99c1eb619a5224a7ef7d8338c70961cd98e2d7d` · no-sort-check `22ccda36321cdbd4b9bd1c651deab467157ecfe88347d0ed9a3e515b035724dc` |
| M1 새 상수(§6-1 규칙이 낸 값) | 슈트 확인 창 **167~273** · 슈트 가득 **50** · 발사 지연 뺄셈 상수 **6**(통계는 §4-4) |
| M1 래더(`ladders/cell-b-m1/`) | 정답 `06db7026ff35e3a705578200f73318948ac9e5006fafcfbcbf5cb0bfd80a59de` · push-timing-off `55fb9267a1a1a695be266e762656b7e890d73845c1487e2ee84dd56ab31cdae7` · ignore-curtain `e83a8a206378585517571be4c1a8c2116d4f38efcbe88bb5e0f8212f14ac5592` · no-sort-check `e5cfa34d52676093184fb5bb39f42a256e221a8b04b7d1ec253bc7ee64093bb3` |
| M1 표 · 교정 기록 | 새 상수 표 `m1-constants.json` `6006ae805bce462fb8c066577da9435693368ad4eb57554411806735beee6321` · M1 참조 매개변수표 `m1-reference-params.json` `2be815a93906550482f962c44fd62150d0b14308e652c6265df29654c98f30a0` · 재생성 보고 `regenerate-report.json` `98585a4cf7dee8d728cd1661c0433e37fcdb961e2db3a758d97b6e9d3d6e8330` · 교정 기록 `calibration.json` `dfcf77bd86f7841a62eb781777951b7a720a6dfdbf2bac6c21b2097e34cbdd46` |
| E4 변종 목록 | TR-2026-03 `variants/TR-03_변종목록_v1.json` `bc61eab488b39600724eda60071b1d86da05af33b56965582464ebcb62ef1f67` · `ladders-sha256.json` `5718dbb801a94c8521449afb6d931f9552f312e957303cc2e726bfb8a622688a` |
| 스크립트(`고정입력_TR-05/bridge/`) | `run.py` `289f0dc762e303c8ea6699d56f50fc0ee35e1765a655f0076fa0468f26cb763d` · `transport.py` `fdfc60eec541f8b29eae6cb4a4279faae279cbae09f29ecefd8a37d9152e4c6d` · `tr05.py` `d6eb905f8a1c79c7684591cd1c5f96d0c54e84291c845c9a37bd1a17bb5ce2a1` · `common.py` `83bde9628dc477bc4280e93d851f8f32a1d96017892097b61d705f7e369c5955` · `refcheck.py` `6030bd65c9abe896dad8a1e7b7d7b81b13eeeb60fa2858a0ca6b1fdd9ad3022a` · `seed_table.py` `6a9f50fc318a074d40303706e904db02fff42adc3b7e1caacf9ae649c4031e18` · `round.py` `90cfe55c46c04732c1407148f8c689af7cf119e2938ee5b98de940f93b95cd03` · `replay.py` `ccc9fb659708742e1778b8f226271cebef8f9a4306ceb1d4c1660ec7480c979e` · `calibrate.py` `bc6d42b8eb3b3a6742cdc2e2613ef71a1e7e46def353942ad9a37081808d5532` · `probe_engine.mjs` `529219e2d2200ad51cd180cdb94dffe544ea16e84c47d82952bc0a991ab9e76e` · `regenerate_m1.py` `323179f87bc655dc2614ebadde29b686e115ff26c1c6116c877fd1277882b5cb` · `generate_3i.py` `114fbff8fadd4b8c114717b6aabb6d78f1c0dac76623b81580d2469462e429d6` · `classify.py` `ca6c354e0d7f6465d29076767814139b7533f9331a1a82ee4be18a47d3008a07` · `tables.py` `cb82aedca5687505532c98a02639ff1181a5bf646c27966fb69b616fd0874d1d` · `recompute.py` `a5e694044937926ddf87bd7fb633b738ca50b0ec9d7d3a4d5c73e40de70a856b` · `public.py` `43e8fe9f92abe84d3623589d139cb9754a7de64293046781738cee8f318744fc` · `patent_check.py` `2be02791209e20215ebef1111df51ba63e584eeecfb366512f749374a18cddc0` · `engine.mjs` `bd147cc2f5d1ff3fd8683706e6d8b3f077ee16610ebf71c3d6a90915bf2021f2` |
| 고정값 파일 | `fixed.json` `532167ac1078b01ea5b4b9a42dd3ca2879a3d23e707dccab9c89b8024eae4442` |
| 출처표 | `SOURCES.json` `88d0920e2880977e7bf93c4f21c8debe4e1affa975e6a33c854613599447d98d` |

**공식 회차 실행 명령(고정 — v1.0 커밋 뒤에만)**

```
python3 bridge/round.py run --app <vexplor_studio_native> --seed-table seed-table.json --seed-table-sha256 d02d62f3975411e3d01b3a58d0c50eb740ffe2b46375c04928788b4bdee3c320 --fixed fixed.json --fixed-sha256 532167ac1078b01ea5b4b9a42dd3ca2879a3d23e707dccab9c89b8024eae4442 --e4-variants <TR-2026-03 variants/TR-03_변종목록_v1.json> --e4-sha <TR-2026-03 variants/ladders-sha256.json> --out <회차>
python3 bridge/tables.py <회차> --out <tables.json>
python3 bridge/public.py build <회차> --out <묶음> --fixed fixed.json --seed-table seed-table.json --names <비공개 계정 이름 파일>
python3 bridge/recompute.py <묶음> --tables <tables.json>
python3 bridge/patent_check.py --tool ~/e5-work/patent/patent_scan.py --prereg TR-2026-05_사전등록_v1.0.md --bundle <묶음> --out <결과>
```

### 10-1. 물리값 목록 (사람이 읽는 표)

앱 코드(`physics_transport.cpp` `PhysicsTransport::defaults()` · `sort_transport.cpp` `SortTransport::defaults()`, 커밋 `ac78d02`)의 목록을 순서대로 옮겼다. 셀 JSON `"physics":{"values":{이름: 값}}` 으로 바꿀 수 있고, 바꾸면 두 해시가 모두 바뀐다. 출처 칸: **가정** = 측정 · 장치 자료 없이 정한 값, **장치 자료** = plc-devices 장치 정의(판)에서 옮긴 값, **파생** = 빠른 코어 규칙 · 측정에서 정한 값, **감도** = 감도 · 모형 가정 설정용 스위치(기본값에서 동작 영향 없음). 부품 치수 · 질량 · 마찰 · 반발 계수, 벨트 · 슈트 · 원호 마찰 계수(`design.transition_mu` 등), 중력은 이 목록이 아니라 셀 · 장치 정의에서 오며 values 해시에 장면 MJCF 로 들어간다.

**셀 A(15개, 규칙 v1)**

| 이름 | 기본값 | 단위 | 뜻 | 출처 |
| --- | --- | --- | --- | --- |
| `fixed_step_s` | 0.001 | s | MuJoCo 고정 스텝. 50 ms 틱 = 정수 스텝 수 | 가정(엔진 설정) |
| `deck_thickness_m` | 0.02 | m | 데크 상자 두께(데크 윗면 아래) | 가정 |
| `guide_height_m` | 0.03 | m | 옆 가이드 높이(데크 윗면 위) | 가정 |
| `guide_thickness_m` | 0.01 | m | 옆 가이드 두께 | 가정 |
| `guide_clearance_m` | 0 | m | 데크 가장자리와 가이드 안쪽 면 사이 틈 | 가정 |
| `floor_thickness_m` | 0.05 | m | 바닥 상자 두께(y = 0 아래) | 가정 |
| `floor_size_m` | 20 | m | 바닥 상자 한 변 길이 | 가정 |
| `friction_static_weight` | 1 | — | 부품 마찰 = w · 정지 마찰 + (1 − w) · 운동 마찰(두 면의 작은 값) | 가정 |
| `torsional_friction_m` | 0.005 | m | 부품 비틀림 마찰(condim 6) | 가정 |
| `rolling_friction_m` | 0.0001 | m | 부품 구름 마찰(condim 6) | 가정 |
| `deck_restitution` | 0 | — | 데크 접촉 반발 | 가정 |
| `guide_restitution` | 0 | — | 가이드 접촉 반발 | 가정 |
| `floor_restitution` | 0 | — | 바닥 접촉 반발 | 가정 |
| `tilt_flag_rad` | 0.0349 | rad | 보고 표시: 데크 위 부품 기울기가 이 값(2°)을 넘으면 `tilt_flag` | 가정(보고용) |
| `friction_scale` | 1 | — | 모든 부품 접촉 마찰 계수 배율(M 전용) | 감도 |

**셀 B(3i)(32개, 규칙 v4)**

| 이름 | 기본값 | 단위 | 뜻 | 출처 |
| --- | --- | --- | --- | --- |
| `fixed_step_s` | 0.001 | s | MuJoCo 고정 스텝. 10 ms 틱 = 정수 스텝 수 | 가정(엔진 설정) |
| `deck_thickness_m` | 0.02 | m | 데크 상자 두께 | 가정 |
| `guide_height_m` | 0.03 | m | 옆 가이드 높이 | 가정 |
| `guide_thickness_m` | 0.01 | m | 옆 가이드 두께 | 가정 |
| `guide_clearance_m` | 0 | m | 데크 가장자리와 가이드 사이 틈 | 가정 |
| `floor_thickness_m` | 0.05 | m | 바닥 상자 두께 | 가정 |
| `floor_size_m` | 40 | m | 바닥 상자 한 변(데크 아래 중심) | 가정 |
| `deck_friction_static_weight` | 1 | — | 데크-부품 마찰 = w · min(벨트, 부품 정지 마찰) + (1 − w) · min(벨트, 부품 운동 마찰) | 가정 |
| `chute_friction_static_weight` | 0 | — | 슈트 경사면-부품 마찰의 같은 혼합 가중(0 = 운동 마찰) | 가정 |
| `part_friction_static_weight` | 1 | — | 부품끼리 마찰 = w · 정지 + (1 − w) · 운동 | 가정 |
| `wall_friction` | 0 | — | 가이드 · 센터링 벽 · 슈트 벽 · 끝벽 · 출력 끝 쿠션 마찰 | 파생(빠른 코어는 마찰 없이 클램프) |
| `floor_friction` | 0.5 | — | 바닥-부품 마찰(바닥에 떨어진 부품은 공정 밖) | 가정 |
| `torsional_friction_m` | 0.005 | m | 모든 접촉의 비틀림 마찰(condim 6) | 가정 |
| `rolling_friction_m` | 0.0001 | m | 모든 접촉의 구름 마찰(condim 6) | 가정 |
| `static_restitution` | 0 | — | 정적 면 · 판의 반발(접촉 솔버 매개변수를 정함) | 가정 |
| `transition_facets` | 10 | 개 | 원호(반지름 `design.transition_radius_m`, 슈트 각)를 나누는 현 면 수 | 가정(이산화) |
| `transition_thickness_m` | 0.02 | m | 원호 면 · 슈트 경사면 두께 | 가정 |
| `chute_wall_thickness_m` | 0.01 | m | 슈트 옆벽 · 끝벽 두께 | 가정 |
| `centering_wall_bottom_m` | 0.015 | m | 센터링 벽 아래 끝 높이(데크 위) | 장치 자료(str-cell-centering 1.1.0) |
| `centering_wall_height_m` | 0.02 | m | 센터링 벽 높이 | 장치 자료(str-cell-centering 1.1.0) |
| `centering_wall_thickness_m` | 0.008 | m | 센터링 벽 두께 | 장치 자료(str-cell-centering 1.1.0) |
| `output_stop_bottom_m` | 0.0025 | m | 출력 끝 쿠션 아래 끝 높이 | 장치 자료(str-cell-output-stop 1.1.0) |
| `output_stop_height_m` | 0.1375 | m | 출력 끝 쿠션 높이 | 장치 자료(str-cell-output-stop 1.1.0) |
| `output_stop_thickness_m` | 0.01 | m | 출력 끝 쿠션 두께 | 장치 자료(str-cell-output-stop 1.1.0) |
| `plate_thickness_m` | 0.012 | m | 푸셔 판 두께 | 장치 자료(asm-pusher 1.5.0 design_loads) |
| `center_contact_tolerance_m` | 0.002 | m | CENTER-SNAP: 발자국 모서리가 센터링 벽에 파고드는 소프트 접촉 침투 허용(측정 최대 1.66 mm, z0 ≤ 0.06 m) | 파생(측정) |
| `output_contact_tolerance_m` | 0.002 | m | 출력 도착(route 2): x ≥ 빠른 코어 출력 상한 − 이 값(접촉은 상한에 정확히 닿지 못함) | 가정 |
| `tilt_flag_rad` | 0.0349 | rad | 보고 표시: 데크 위 부품 기울기 2° 초과 | 가정(보고용) |
| `friction_scale` | 1 | — | 부품 접촉의 모든 미끄럼 마찰(정적 면 · 판 · 부품끼리)과 슈트 x 힘 목표(chute_x_mu) 배율(M 전용) | 감도 |
| `transition_mu_scale` | 1 | — | 원호 면 마찰(`design.transition_mu`)과 슈트 x 힘이 빼는 원호 등방분 배율(M 전용) | 감도 |
| `chute_x_force` | 1 | 0/1 | 1: 슈트 부품에 x 방향 추가 힘(빠른 규칙 chute_x_mu 감속을 따름), 0: 끔 · 등방 마찰만(M 전용) | 감도(기본 1 = 이식 규칙 v3 동작) |
| `sensor_footprint_rotated` | 0 | 0/1 | 0: sen-photo 표적 = 고정 축 정렬 부품 상자, 1: MuJoCo 자세 부품 상자의 센서 좌표계 외접 상자(M 전용) | 감도(모형 가정 설정) |

## 11. 주장하지 않는 것 · 한계 [동결]

- 시뮬레이션이다. 어느 모형도 실물 셀 · 실물 상자와 대조하지 않았다. **MuJoCo 모형이 더 옳다고 주장하지 않는다.**
- 이 편의 [PASS] · [FAIL] · 「검출」은 시뮬레이터 안에서 §3-5 의 판정 규칙이 낸 값이다. 래더가 실물 설비에서 올바르거나 안전하다는 뜻이 아니며, 어느 모형으로 한 플랜트 연결 시험도 현장 시운전을 대신한다고 주장하지 않는다. 검출 수는 이 편이 고른 음성 래더 5종의 값이고, 어떤 제품의 결함 검출 성능도 나타내지 않는다.
- MuJoCo 이송 코드는 이 실험을 위해 만든 개발 브랜치(`feature/tr05-e2`)의 코드이며 출시된 기능이 아니다. 결과는 VEXPLOR 제품의 동작 · 성능을 말하지 않는다.
- 셀 두 개(셀 A 왕복, 셀 B(3i))다. 포장 셀 · 셀 B 3j/3k 변형은 MuJoCo 모드가 없어 범위 밖이다.
- **TR-2026-02 · 03 · 04 의 셀 B(3k) 결과와 이 편의 셀 B(3i) 결과는 합치거나 나란히 놓고 해석하지 않는다.** 셀 설계 · 래더 · 음성 래더 셋 · 플랫폼이 다르다(§3-3). 시드 번호가 같아도 같은 배치가 아니다. 이 편의 결과로 TR-2026-03 · 04 의 결론을 고치거나 뒷받침하지 않는다 — 그 편들의 셀 B 판정이 플랜트 모형 선택에 얼마나 민감한지는, 3k 셀에 MuJoCo 모형이 생기기 전에는 이 편으로 알 수 없다. 셀 A 와 E4(TR-2026-03 셀 A 변종)는 같은 래더 파일이지만 실행 플랫폼이 다르므로 판정 단위로만 나란히 적는다.
- 경로 A: 액추에이터는 두 모형이 같은 코어 궤적이다. 실린더 힘 · 강성 한계, 판의 동역학은 모델하지 않았다(행정 시간 초과 · 리드 스위치 차이는 이 모형에서 생길 수 없다). 차이는 부품 이송 · 접촉에서만 생긴다.
- 모형 M 은 묶음이다(§1). 뒤바뀜의 원인을 물리 · 이식 규칙 · 장부로 나눈 것은 §7 원인 분류와 E1 사전 대응이며 확인 주장이 아니다. 이식 허용치(2 mm 둘)는 감도 실행에서 바꾸지 않았다.
- MuJoCo 쪽 물리값(가이드 · 벽 치수, 벽 마찰 0, 정지 마찰 가중, 접촉 허용치 2 mm 둘, 원호 면 수)은 가정값이며 측정하지 않았다. solref 시간 상수 0.01 s · solimp(0.95, 0.99, 0.001)는 코드에 고정된 값이고, 접촉 허용치 2 mm 둘은 이 강성에서 잰 침투(최대 1.66 mm)에 맞춘 것이다(CENTER-SNAP 여유 0.34 mm). 판정이 상자 회전에 민감하다(§4) — 감도 실행(§6-4)으로 그 폭만 보인다.
- 센서는 기본으로 축 정렬 고정 치수 상자 + 부품 중심을 쓴다. MuJoCo 에서 상자가 돌아도 기본 센서 윤곽은 돌지 않는다(회전한 실제 윤곽 최대 0.265 m). 이 가정의 효과는 모형 가정 설정 「센서 윤곽」으로 보인다. P8 의 8개 설정에는 yaw 원인으로 가장 직접적인 센서 윤곽 · 판 마찰 · 데크 운동 마찰이 들어 있지 않다(앞 둘은 모형 가정 설정으로 보고, 판 마찰은 넣지 않았다).
- MuJoCo 솔버가 반복 80 에 닿아 수렴하지 못해도 경고가 나지 않으므로 `[PLANT_ERROR]` 로 잡히지 않는다.
- 정답 래더 상수의 일부는 빠른 모형의 계산 이력에서 정해졌고 그 절차는 문서로 없다(§3-3). 조건 M1 은 이 편이 정의한 재교정 규칙이며 원래 절차의 재현이 아니다. M1 은 슈트 용량을 바꾸지 않는다. 셀 A 상수는 출처가 없어 재교정하지 않았다.
- `no-sort-check` 는 3i 에서 기대 사유를 낼 수 없어 결함 검출 주 지표에 들어가지 않는다. 셀 B 음성의 주 지표는 2종(24쌍)뿐이다. `recovery` · `no-sort-check` 는 묶음 5 배치 하나에서만 돌리므로 M 에서 슈트 가득 잠금과 겹칠 수 있다.
- 셀 A 정답 래더는 공식 입력과 같은 입력의 M0 결과를 등록 전에 봤으므로 확인 대상이 아니다.
- 참조 일치 무효 범위(첫 잠금 전)와 예외 모양은 개발 실행을 본 뒤에 정했다.
- CENTER-ENTRY 는 M 에서 일어날 수 없고, CENTER-SNAP 의 양성 사례는 어느 모형에서도 시험되지 않았다.
- 결정성 · 비교는 한 기계 · 한 빌드(linux-arm64, Clang 21.1.8, 위 libmujoco)에서만 주장한다. TR-2026-02 · 03 · 04 는 macOS 에서 돌았으므로 그 실행과 비트 단위로 비교하지 않는다(F 게이트는 항목 단위로 같았다).
- 배치는 시드 규칙으로 뽑은 12개이고 불량 개수로 묶음을 나눴다. 불량률 0.2 의 자연 분포를 대표하지 않는다.
- 원래 방법론 심사 원문(2026-09-29)은 이 PC 에서 찾지 못해 v0.2 의 요약으로만 옮겼다. v1.0 전에 원문과 대조하지 못하면 그 사실을 v1.0 에도 적는다.
- **생성형 AI 관여**: MuJoCo 이송 코드, 실행 도구, 이 문안 작성과 교차 검토에 LLM 코딩 에이전트(Claude(Anthropic), 이전 단계는 Codex(OpenAI) 포함)가 관여했다. 여기서 「독립」 검토는 서로의 산출과 작성 맥락을 읽지 않은 에이전트 실행을 뜻하며 사람 검토자가 아니다. 코드를 사람이 줄 단위로 검수한 적은 없다.

## 12. 공개 묶음 구성 (확정 — 대표 2026-10-08 승인 범위, 머리의 「대표 확인」 행)

| 파일 | 내용 | 라이선스 |
| --- | --- | --- |
| `TR-2026-05.md` · `.pdf` | 보고서 | CC BY 4.0 |
| `TR-2026-05/MANIFEST.md` | 파일별 sha256 · 라이선스 | — |
| 사전 등록 동결판(v0.6) · 개정 1 · 고정판(v1.0) · 동결 범위 문서(`TR-05_v0.6_동결범위_2026-10-08.md` — 동결 절 해시를 다시 계산하는 규칙) | 공개 해시와 대조용 | CC BY 4.0 |
| 시드 표 `seed-table.json` · 교정 기록 `calibration.json` · M1 새 상수 표 `m1-constants.json` · M1 참조 매개변수표 `m1-reference-params.json` · 재생성 보고 `regenerate-report.json` · 고정값 파일 `fixed.json` · 출처표 `SOURCES.json`(경로가 있으면 공개본 변환으로 뺀 사본, 원본 sha256 함께) | 시드 · 교정 · 고정 입력 대조 | CC BY 4.0 |
| `results.jsonl` · `run.json` · `tables.json` · 실행별 축약 파일(범주 · 판정 · 장부 무관 판정 · 사건 코드 묶음 · 경로 · 참조 일치 · M 진단 요약, 절대 경로 없음) | 결과 · 독립 검산 입력 | CC BY 4.0 |
| 열린 고리 에지 표 · 감도 표 · 모형 가정 설정 표 · 시드 표 · 물리값 목록(이름 · 값 · 뜻) · 해시 표 · 두 모형 기능 차이 표 · E1 대응표 · M1 새 상수 표 | 판정 재계산 · 조건 확인 | CC BY 4.0 |
| 양성 대조 기준(`plc-devices-3i-4a-seed-results.json` · macOS `3i-final-2` 요약)과 양성 대조 결과(양성 대조 1 개정 전 · 뒤, 무효로 보존한 첫 양성 대조 2 의 요약, 개정 1 뒤 양성 대조 2 의 표 · 공개본) · 교정 실행 요약(`실행/tr05-calib-1/` 의 요약 · 해시 목록) | §8 양성 대조 · §4-4 를 독자가 대조 | CC BY 4.0 |
| `experiments/S2/criteria-3i.md`(바이트 그대로) | §3-4 기대 사유 · L2 근거 대조 | CC BY 4.0 |
| 실행기 공개본 — `bridge/` 의 `run.py` · `tr05.py` · `transport.py` · `round.py` · `seed_table.py` · `calibrate.py` · `regenerate_m1.py` · `tables.py` · `recompute.py` · `public.py` · `patent_check.py` 와 도움 모듈 `common.py` · `refcheck.py` · `classify.py` · `replay.py` · `probe_engine.mjs` | 공개본에서 본문 숫자를 다시 계산(교정 측정기 `calibrate.py` 는 비공개 `engine.mjs` 가 있어야 돌므로 독자는 교정 측정을 다시 할 수 없다 — 교정 기록과 새 상수 표는 공개) | MIT |
| 셀 A 정답 · 음성 래더 공개본 | TR-2026-02 에 이미 공개된 것과 같음 | 기존과 같음 |
| 셀 B(3i) 정답 래더(원래 · M1) 공개본 | D8 — 공개(TR-2026-03 의 3k 정답 래더 공개본과 같은 방식) | 기존 정답 래더 공개본과 같음 |

- **공개하지 않는 것**: 제품 소스(앱 · extctl · MuJoCo 이송 코드), 셀 파일 · io-map · 태그 맵(`cells/*.tagmap.*`) · `cells/3i-*.json` · 참조 논리 · 장치 정의, 래더 생성기(`bridge/generate_3i.py` · `ladder_dsl.py` · `design_3f.py` · `generate.py`)와 고친 래더 엔진 `bridge/engine.mjs`(sha256 만), 셀 B 음성 래더(원래 3종 · M1 재생성 3종 모두 sha256 만), 동봉 plc-simulator 사본 · 다리 원본 사본(출처 커밋과 sha256 만), 틱별 추적 파일(용량), 앱 stderr 로그(계정 경로), 본문에 이름만 나오는 사내 개발 기록(`e2_*` · `_agent/` 문서 · 재개 계획 — 판정에 쓰지 않고 근거는 이 문서에 글로 적었다).
- 공개하는 래더는 TR-2026-02 · 03 의 공개본 변환과 같은 방식으로 `marker` 줄을 뺀 공개본이며, 실행본 sha256 을 함께 적는다.
- 해시 입력 전문(컴파일된 장면 MJCF)은 제품 이송 코드가 만든 산출물이라 공개하지 않고 해시값만 공개한다. 그래서 독자는 `values_sha256` · `setup_sha256` 을 다시 계산할 수 없고, 실행 기록의 값이 시드 표의 값과 같은지만 확인할 수 있다.
- MuJoCo(Google DeepMind, Apache-2.0)는 묶음에 넣지 않고 버전과 sha256 만 적는다. MuJoCo · NVIDIA GB10 · Ubuntu 는 각 소유자의 상표이며 이 보고서는 그들과 관계가 없다는 고지를 보고서에 넣는다.
- **특허 · 방어적 공개**(대표 2026-10-08 「추천대로」): 이 편이 기술한 MuJoCo 부품 이송 규칙과 모형 — 이송 규칙 v1(셀 A) · v3(셀 B, 공식 빌드에서 감도 값 추가로 v4), 물리값 목록, 장면 구성(코어 궤적을 동적 판에 써 넣는 혼합 플랜트, 틱 단위 복사 · 확정, 슈트 x 힘, `CHUTE-HOLD`, 설정 해시와 장면 해시의 분리) — 과 M1 재교정 규칙에는 특허를 출원하지 않는다. 이 보고서가 그 공개 역할을 한다. 보고서의 라이선스 절과 `MANIFEST.md` 에 TR-2026-06 · 07 과 같은 문장으로 넣는다: 「No patent will be filed on the MuJoCo part-transport rules and model described in this study (transport rules v1/v3, the physics values lists and the scene construction); this report serves as their disclosure.」
- 공개 전에 묶음 전체(압축 안 포함)에서 로컬 절대 경로 · 홈 폴더 · 계정 이름 · 세션 경로 · 비공개 호스트 URL · 메일 주소 · `CONFIDENTIAL` 표지를 문자열로 찾고(일부러 넣은 양성 대조 포함, `public.py scan`) 0 건이어야 공개한다. 찾을 계정 이름 목록은 비공개 입력(`--names`)이며 공개하지 않는다.

## 13. 대안 (본문에 넣지 않은 설계) [동결]

| 대안 | 넣지 않은 이유 |
| --- | --- |
| 셀 B 3k 래더(TR-03 · 04 와 같은 것) | MuJoCo 모드가 3j/3k 설계를 거부한다. 3k 이식은 위치 규칙(feed_boundary 등)에 물리 대응이 없어 별도 개발 |
| 경로 B(실린더도 힘 · 강성 슬라이더) | 실물 근거 없는 상수가 늘어 재교정 조건이 커진다 |
| 출력 동등성(Q 일치)을 판정 기준으로 | 두 모형의 센서 시각이 다르면 Q 는 당연히 다르다. 판정 · 사건 · 검출만 비교한다 |
| 참조 일치를 실행 전체에서 무효 기준으로 | 문서화된 1 스캔 차이와 잠금 뒤 램프 표시 차이로 모든 회차가 무효가 된다(§8 ②) |
| `no-sort-check` 에 새 다리 판정 규칙을 만들어 주 지표에 넣기 | 등록 직전에 판정 규칙을 새로 만들면 그 규칙이 결과에 맞춰질 위험이 있다 |
| 결측을 예측에 불리한 쪽으로만 세기 | 정보가 없는 결과를 [틀림] 으로 적게 된다. 양쪽 채움으로 [판정 불가] 를 낸다 |
| M1 슈트 확인 창을 중심만 옮기기 | M 의 퍼짐(최대 +390 ms)만으로 FaultCode 13 이 나와 질문 3 이 상수 출처와 무관하게 정해진다 |
| 발사 지연을 시각 차이로 재교정 | 원래 기준(「일찍 닿음」)은 접촉 위치였다. 시각 기준은 부호가 기준 시각에 따라 뒤집힌다 |
| 판 마찰 배율 · 솔버 반복 진단 | 앱 변경이 필요하고 반드시 고칠 것이 아니다. 한계로 적는다(§11) |
| 측면 초기 위치 무작위화 · 피치 흔들림 | M 에서 \|z\| > 0.125 는 거부. ±5 mm 섭동만 모형 가정 설정으로 넣었다 |
| `chute.jam` · 압력 손실 · 막대 끼임 고장 주입 | 다리에 주입 시나리오가 없고 기존 편들도 쓰지 않았다 |
| 불량 6개 이상 묶음 | 빠른 모형에서도 슈트 대기열을 넘을 수 있어 모형 차이와 섞인다 |
| 다리 `normal` 에 수거 자극 추가 | 기존 시나리오를 바꾸지 않는다(D15) |

## 13-1. 특허 사전 확인

- 대상: 등록 제10-2904772호 · 제10-3003470호 · 출원 KP26038.
- 도구: TR-2026-08(E5)이 쓴 핵심어 대조 도구(`~/e5-work/patent/patent_scan.py`, 핵심어 목록 · 양성 대조 포함 — TR-04 와 같은 방식)를 `고정입력_TR-05/bridge/patent_check.py` 로 불러 쓴다(도구는 고치지 않음). 도구의 양성 대조 파일은 16건이 잡히고 깨끗한 글은 0 건이다.
- **최종 실행(동결 뒤, 대상 22개 — 동결판 v0.6 · 개정 1 · 실행기 공개본 · 표 · 검산 · 공개본 변환 스크립트 · 3i 정답 래더 공개본(원래 · M1) · 양성 대조 2 공개본 묶음): 10건 — 5 핵심어 × 2회, 모두 v0.6 §13-1 의 구성 대조 부정문(「그래프 저장소 · 검색 증강 · 변화율 동적 속성 · SHACL 제약 · 명령 선제 차단은 없다」) 자체다(v0.6 에는 그 문장이 결과 줄과 구성 대조 줄에 두 번 있다). 개정 1 · 스크립트 · 래더(원래 · M1) · 공개본 묶음은 0 건 — 겹침 없음.** 결과 파일 `실행/tr05-calib-1/patent_check_v06.json` · `patent_check_a1.json`. 이전 실행(v0.5 기준)은 5건(같은 문장 한 줄).
- 구성 대조: 이 실험은 플랜트 모형 두 개에 같은 래더를 붙여 사건 · 판정을 비교한다. 그래프 저장소 · 검색 증강 · 변화율 동적 속성 · SHACL 제약 · 명령 선제 차단은 없다.
- 공식 회차 공개본 묶음이 생기면 같은 명령으로 다시 돌려 보고서에 적는다.

## 14. 고정 뒤 순서

1. ~~E2-1 · E2-2 · E2-3 구현과 코드 검토~~ — 2026-10-08.
2. ~~v0.3 → v0.4 → AI 검토 4건 → v0.5~~ — 2026-10-08.
3. ~~구현 I1~I16(앱 `ac78d02` · 실행기 개발판) → v0.6~~ — 2026-10-08.
4. ~~예측 · 분석 동결: v0.6 동결 절 해시 공개 커밋~~ — tech-reports `3a12187`(2026-10-08 13:33:43 KST).
5. ~~양성 대조 1 → 시드 표(적재만) → 교정 12 실행 → `calibrate.py` → M1 래더 · 매개변수표 → 양성 대조 2(무효, 보존)~~ — 2026-10-08.
6. ~~개정 1 공개 커밋~~ — tech-reports `1ac8c13`(13:55:28 KST) → ~~양성 대조 1 재실행 · 양성 대조 2 재실행(유효) · 특허 사전 확인 재실행 · 최종 고정값 파일~~ — 2026-10-08.
7. **v1.0 해시 공개 커밋**: 이 파일의 sha256 을 공개 저장소 `PREREGISTRATIONS.md` 에 「TR-2026-05 (v1.0)」 행으로 커밋한다. 이 커밋 전에는 공식 회차를 돌리지 않는다.
8. **공식 회차**: §10 의 공식 회차 실행 명령(시드 표 `d02d62f3…` · 고정값 파일 `532167ac…` 해시 확인 뒤 시작) — 주 162 · M 2회째 106 · F 게이트 2회째 9 · 열린 고리 14 · P8 감도 156 · 모형 가정 설정 10 × (f + 2) · E4 100. 무효면 §8 의 재시도 규칙.
9. **독립 검산**: `tables.py` → `public.py build`(공개본 · 문자열 검사) → `recompute.py`(원 회차 표 · 공개본 표 둘 다와 대조, 차이 0 이어야 함) → 특허 사전 확인 재실행.
10. **보고서**: 결과 · 표 · 예측 판정을 보고서로 쓰고, 공개 전 심사 · 팩트체크를 거쳐 §12 의 묶음으로 공개한다(TR-2026-07 과 같은 절차).

## 15. 작업 목록 (상태 — v1.0 고정 시점)

- [완료] 앱 `ac78d02`(ctest 11/11, 기본값에서 F 응답 바이트 · M 적분 상태 · 해시 기본값이 `0edb740` 과 같음).
- [완료] 실행기 · 분석 `고정입력_TR-05/bridge/`(자기 시험 13종 모두 통과 — 개정 1 뒤 `refcheck.py` 12/12 · 사례 9/9 포함, 공개 스크립트 14개 문자열 검사 0 건).
- [완료] 양성 대조 1(개정 전 · 뒤), 시드 표, 교정 12 실행, M1 래더 4 · 표 3, 양성 대조 2(개정 뒤 유효), 특허 사전 확인, 고정값 파일(두 번 만들어 같음).
- [남음] v1.0 해시 공개 커밋 → 공식 회차 → 독립 검산 → 보고서(§14-7~10).

## v1.0 변경 기록 (v0.6 → v1.0, 2026-10-08)

[동결] 절(§1 · §3 · §5 · §6 · §7 · §8 · §9 · §11 · §13)은 바꾸지 않았다(동결 절 sha256 `888cfd52…` 그대로). 바꾼 곳:

| 절 | 변경 | 출처 |
| --- | --- | --- |
| 머리 | 버전 v1.0 · 상태 「고정」, 동결 커밋 `3a12187` · 개정 1 커밋 `1ac8c13` 행 | 실행 상태 6 |
| 동결 뒤 변경(신설) | 개정 1 · `round.py --dev` 수정 · 고정값 파일 범위 확장 · 개정 1 구현 파일 · `SOURCES.json` 의 초안 해시(순환) · 기존 ctest 기록 사용 | 실행 상태 6 |
| §4 | 4-4 「동결 뒤에 본 개발 관찰」 신설(양성 대조 1 과 재실행, 교정 실행과 결과, 무효인 첫 양성 대조 2, 개정 1 뒤 양성 대조 2) | 실행 상태 6 |
| §10 | 최종 해시 · 값 전부(빌드 · 실행 파일 · libmujoco · Node · 셀 · io-map · 설계 파일 · 참조 논리 · 래더 원래 · M1 · M1 표 · 교정 기록 · 새 상수 167~273 / 50 / 6 · 시드 표 · 시드별 values · E4 · 스크립트 · `fixed.json` · `SOURCES.json`), 공식 회차 명령, 10-1 물리값 목록(셀 A 15 · 셀 B 32, 이름 · 기본값 · 단위 · 뜻 · 출처) | 실행 상태 6 · 앱 코드 |
| §12 | 공개 목록 확정(시드 표 · 교정 기록 · M1 상수 표 · 매개변수표 · 고정값 파일 · 출처표 · 개정 1 · 동결 범위 문서 · 양성 대조 결과) | 실행 상태 5 · 6 |
| §13-1 | 최종 결과 10건 | 실행 상태 6 |
| §14 · §15 | 고정 뒤 순서(v1.0 해시 커밋 → 공식 회차 → 독립 검산 → 보고서)와 상태 | 리드 지시 |

v0.6 이전의 변경 기록은 `TR-2026-05_사전등록_v0.6.md` · `v0.5.md` · `v0.4.md` 끝에 있다.
